from __future__ import annotations

from typing import Any

import pytest

from schemas.apis.condenser_api.response_schemas import (
    FindProposals,
    FindRecurrentTransfers,
    GetAccountCount,
    GetAccountHistory,
    GetAccountReputations,
    GetAccounts,
    GetActiveVotes,
    GetActiveWitnesses,
    GetBlock,
    GetBlockHeader,
    GetBlog,
    GetBlogEntries,
    GetChainProperties,
    GetCommentDiscussionsByPayout,
    GetConfig,
    GetContent,
    GetContentReplies,
    GetCurrentMedianHistoryPrice,
    GetDiscussionsByAuthorBeforeDate,
    GetDiscussionsByBlog,
    GetDiscussionsByComments,
    GetDiscussionsByCreated,
    GetDiscussionsByFeed,
    GetDiscussionsByHot,
    GetDiscussionsByTrending,
    GetDynamicGlobalProperties,
    GetEscrow,
    GetFeed,
    GetFeedHistory,
    GetFollowCount,
    GetFollowers,
    GetHardforkVersion,
    GetMarketHistoryBuckets,
    GetNextScheduledHardfork,
    GetOpsInBlock,
    GetOrderBook,
    GetPostDiscussionsByPayout,
    GetRebloggedBy,
    GetRecentTrades,
    GetRepliesByLastUpdate,
    GetRewardFund,
    GetTicker,
    GetTradeHistory,
    GetTransaction,
    GetTransactionHex,
    GetTrendingTags,
    GetVersion,
    GetVolume,
    GetWithdrawRoutes,
    GetWitnessByAccount,
    GetWitnessCount,
    GetWitnesses,
    GetWitnessesByVote,
    GetWitnessSchedule,
    IsKnownTransaction,
    ListProposals,
    ListProposalVotes,
    LookupAccountNames,
    LookupAccounts,
)
from schemas.jsonrpc import get_response_model

from .responses_from_api import (
    FIND_PROPOSALS,
    FIND_RECURRENT_TRANSFERS,
    GET_ACCOUNT_COUNT,
    GET_ACCOUNT_HISTORY,
    GET_ACCOUNT_REPUTATIONS,
    GET_ACCOUNTS,
    GET_ACTIVE_VOTES,
    GET_ACTIVE_WITNESSES,
    GET_BLOCK,
    GET_BLOCK_HEADER,
    GET_BLOG,
    GET_BLOG_ENTRIES,
    GET_CHAIN_PROPERTIES,
    GET_COMMENT_DISCUSSION_BY_PAYOUT,
    GET_CONFIG,
    GET_CONTENT,
    GET_CONTENT_REPLIES,
    GET_CURRENT_MEDIAN_HISTORY_PRICE,
    GET_DISCUSSIONS_BY_AUTHOR_BEFORE_DATE,
    GET_DISCUSSIONS_BY_BLOG,
    GET_DISCUSSIONS_BY_COMMENTS,
    GET_DISCUSSIONS_BY_CREATED,
    GET_DISCUSSIONS_BY_FEED,
    GET_DISCUSSIONS_BY_HOT,
    GET_DISCUSSIONS_BY_TRENDING,
    GET_DYNAMIC_GLOBAL_PROPERTIES,
    GET_ESCROW,
    GET_FEED,
    GET_FEED_HISTORY,
    GET_FOLLOW_COUNT,
    GET_FOLLOWERS,
    GET_HARDFORK_VERSION,
    GET_MARKET_HISTORY_BUCKETS,
    GET_NEXT_SCHEDULED_HARDFORK,
    GET_OPS_IN_BLOCK,
    GET_ORDER_BOOK,
    GET_POST_DISCUSSION_BY_PAYOUT,
    GET_REBLOGGED_BY,
    GET_RECENT_TRADES,
    GET_REPLIES_BY_LAST_UPDATE,
    GET_REWARD_FUND,
    GET_TICKER,
    GET_TRADE_HISTORY,
    GET_TRANSACTION,
    GET_TRANSACTION_HEX,
    GET_TRENDING_TAGS,
    GET_VERSION,
    GET_VOLUME,
    GET_WITHDRAW_ROUTES,
    GET_WITNESS_BY_ACCOUNT,
    GET_WITNESS_COUNT,
    GET_WITNESS_SCHEDULE,
    GET_WITNESSES,
    GET_WITNESSES_BY_VOTE,
    IS_KNOWN_TRANSACTION,
    LIST_PROPOSAL_VOTES,
    LIST_PROPOSALS,
    LOOKUP_ACCOUNT_NAMES,
    LOOKUP_ACCOUNTS,
)


@pytest.mark.parametrize(
    "schema, parameters",
    [
        (GetDiscussionsByAuthorBeforeDate, GET_DISCUSSIONS_BY_AUTHOR_BEFORE_DATE),
        (GetDiscussionsByBlog, GET_DISCUSSIONS_BY_BLOG),
        (GetDiscussionsByComments, GET_DISCUSSIONS_BY_COMMENTS),
        (GetDiscussionsByCreated, GET_DISCUSSIONS_BY_CREATED),
        (GetDiscussionsByFeed, GET_DISCUSSIONS_BY_FEED),
        (GetDiscussionsByHot, GET_DISCUSSIONS_BY_HOT),
        (GetDiscussionsByTrending, GET_DISCUSSIONS_BY_TRENDING),
        (GetDynamicGlobalProperties, GET_DYNAMIC_GLOBAL_PROPERTIES),
        (GetFeedHistory, GET_FEED_HISTORY),
        (GetPostDiscussionsByPayout, GET_POST_DISCUSSION_BY_PAYOUT),
        (GetRepliesByLastUpdate, GET_REPLIES_BY_LAST_UPDATE),
        (FindProposals, FIND_PROPOSALS),
        (FindRecurrentTransfers, FIND_RECURRENT_TRANSFERS),
        (GetAccountCount, GET_ACCOUNT_COUNT),
        (GetAccountReputations, GET_ACCOUNT_REPUTATIONS),
        (GetAccounts, GET_ACCOUNTS),
        (GetActiveVotes, GET_ACTIVE_VOTES),
        (GetActiveWitnesses, GET_ACTIVE_WITNESSES),
        (GetBlock, GET_BLOCK),
        (GetBlockHeader, GET_BLOCK_HEADER),
        (GetBlog, GET_BLOG),
        (GetBlogEntries, GET_BLOG_ENTRIES),
        (GetChainProperties, GET_CHAIN_PROPERTIES),
        (GetCommentDiscussionsByPayout, GET_COMMENT_DISCUSSION_BY_PAYOUT),
        (GetConfig, GET_CONFIG),
        (GetContent, GET_CONTENT),
        (GetContentReplies, GET_CONTENT_REPLIES),
        (GetCurrentMedianHistoryPrice, GET_CURRENT_MEDIAN_HISTORY_PRICE),
        (GetEscrow, GET_ESCROW),
        (GetFollowCount, GET_FOLLOW_COUNT),
        (GetFollowers, GET_FOLLOWERS),
        (GetHardforkVersion, GET_HARDFORK_VERSION),
        (GetMarketHistoryBuckets, GET_MARKET_HISTORY_BUCKETS),
        (GetNextScheduledHardfork, GET_NEXT_SCHEDULED_HARDFORK),
        (GetOrderBook, GET_ORDER_BOOK),
        (GetRebloggedBy, GET_REBLOGGED_BY),
        (GetRecentTrades, GET_RECENT_TRADES),
        (GetRewardFund, GET_REWARD_FUND),
        (GetTicker, GET_TICKER),
        (GetTradeHistory, GET_TRADE_HISTORY),
        (GetTransactionHex, GET_TRANSACTION_HEX),
        (GetTrendingTags, GET_TRENDING_TAGS),
        (GetVersion, GET_VERSION),
        (GetVolume, GET_VOLUME),
        (GetWithdrawRoutes, GET_WITHDRAW_ROUTES),
        (GetWitnessByAccount, GET_WITNESS_BY_ACCOUNT),
        (GetWitnessCount, GET_WITNESS_COUNT),
        (GetWitnessSchedule, GET_WITNESS_SCHEDULE),
        (GetWitnesses, GET_WITNESSES),
        (GetWitnessesByVote, GET_WITNESSES_BY_VOTE),
        (IsKnownTransaction, IS_KNOWN_TRANSACTION),
        (ListProposalVotes, LIST_PROPOSAL_VOTES),
        (ListProposals, LIST_PROPOSALS),
        (LookupAccountNames, LOOKUP_ACCOUNT_NAMES),
        (LookupAccounts, LOOKUP_ACCOUNTS),
        (GetAccountHistory, GET_ACCOUNT_HISTORY),
        (GetOpsInBlock, GET_OPS_IN_BLOCK),
        (GetTransaction, GET_TRANSACTION),
        (GetFeed, GET_FEED),
    ],
)
def test_condenser_api_correct_values(schema: Any, parameters: Any) -> None:
    # ACT & ASSERT
    get_response_model(schema, **parameters)
