# fmt: off

# WARNING: This code was automatically generated by a script.
# DO NOT EDIT this file manually, as any changes may be overwritten.
# If modifications are needed, please update the generating script instead.

from __future__ import annotations

from typing import Literal, overload

import msgspec

from schemas.operation import Operation
from schemas.operations.virtual.account_created_operation import AccountCreatedOperation
from schemas.operations.virtual.author_reward_operation import AuthorRewardOperation
from schemas.operations.virtual.changed_recovery_account_operation import ChangedRecoveryAccountOperation
from schemas.operations.virtual.clear_null_account_balance_operation import ClearNullAccountBalanceOperation
from schemas.operations.virtual.collateralized_convert_immediate_conversion_operation import (
    CollateralizedConvertImmediateConversionOperation,
)
from schemas.operations.virtual.comment_benefactor_reward_operation import CommentBenefactorRewardOperation
from schemas.operations.virtual.comment_payout_update_operation import CommentPayoutUpdateOperation
from schemas.operations.virtual.comment_reward_operation import CommentRewardOperation
from schemas.operations.virtual.consolidate_treasury_balance_operation import ConsolidateTreasuryBalanceOperation
from schemas.operations.virtual.curation_reward_operation import CurationRewardOperation
from schemas.operations.virtual.declined_voting_rights_operation import DeclinedVotingRightsOperation
from schemas.operations.virtual.delayed_voting_operation import DelayedVotingOperation
from schemas.operations.virtual.dhf_conversion_operation import DhfConversionOperation
from schemas.operations.virtual.dhf_funding_operation import DhfFundingOperation
from schemas.operations.virtual.effective_comment_vote_operation import EffectiveCommentVoteOperation
from schemas.operations.virtual.escrow_approved_operation import EscrowApprovedOperation
from schemas.operations.virtual.escrow_rejected_operation import EscrowRejectedOperation
from schemas.operations.virtual.expired_account_notification_operation import ExpiredAccountNotificationOperation
from schemas.operations.virtual.failed_recurrent_transfer_operation import FailedRecurrentTransferOperation
from schemas.operations.virtual.fill_collateralized_convert_request_operation import (
    FillCollateralizedConvertRequestOperation,
)
from schemas.operations.virtual.fill_convert_request_operation import FillConvertRequestOperation
from schemas.operations.virtual.fill_order_operation import FillOrderOperation
from schemas.operations.virtual.fill_recurrent_transfer_operation import FillRecurrentTransferOperation
from schemas.operations.virtual.fill_transfer_from_savings_operation import FillTransferFromSavingsOperation
from schemas.operations.virtual.fill_vesting_withdraw_operation import FillVestingWithdrawOperation
from schemas.operations.virtual.hardfork_hive_operation import HardforkHiveOperation
from schemas.operations.virtual.hardfork_hive_restore_operation import HardforkHiveRestoreOperation
from schemas.operations.virtual.hardfork_operation import HardforkOperation
from schemas.operations.virtual.ineffective_delete_comment_operation import IneffectiveDeleteCommentOperation
from schemas.operations.virtual.interest_operation import InterestOperation
from schemas.operations.virtual.limit_order_cancelled_operation import LimitOrderCancelledOperation
from schemas.operations.virtual.liquidity_reward_operation import LiquidityRewardOperation
from schemas.operations.virtual.pow_reward_operation import PowRewardOperation
from schemas.operations.virtual.producer_missed_operation import ProducerMissedOperation
from schemas.operations.virtual.producer_reward_operation import ProducerRewardOperation
from schemas.operations.virtual.proposal_fee_operation import ProposalFeeOperation
from schemas.operations.virtual.proposal_pay_operation import ProposalPayOperation
from schemas.operations.virtual.proxy_cleared_operation import ProxyClearedOperation
from schemas.operations.virtual.return_vesting_delegation_operation import ReturnVestingDelegationOperation
from schemas.operations.virtual.shutdown_witness_operation import ShutDownWitnessOperation
from schemas.operations.virtual.system_warning_operation import SystemWarningOperation
from schemas.operations.virtual.transfer_to_vesting_completed_operation import TransferToVestingCompletedOperation
from schemas.operations.virtual.vesting_shares_split_operation import VestingSharesSplitOperation


class HF26Representation(msgspec.Struct):
    value: Operation

    @property
    def type_(self) -> str:
        return self.value.get_name_with_suffix()


class LegacyRepresentation(msgspec.Struct):
    value: Operation

    @property
    def type_(self) -> str:
        return self.value.get_name()

    @overload
    def __getitem__(self, idx: Literal[0]) -> str: ...
    @overload
    def __getitem__(self, idx: Literal[1]) -> Operation: ...

    def __getitem__(self, idx: Literal[0, 1]) -> str | Operation:
        if idx == 0:
            return self.type_
        if idx == 1:
            return self.value
        raise ValueError("Index out of bound <0; 1>")

class HF26RepresentationAccountCreatedOperation(HF26Representation, tag="account_created_operation"):
            value: AccountCreatedOperation


class LegacyRepresentationAccountCreatedOperation(LegacyRepresentation, tag="account_created", array_like=True):
            value: AccountCreatedOperation


class HF26RepresentationAuthorRewardOperation(HF26Representation, tag="author_reward_operation"):
            value: AuthorRewardOperation


class LegacyRepresentationAuthorRewardOperation(LegacyRepresentation, tag="author_reward", array_like=True):
            value: AuthorRewardOperation


class HF26RepresentationChangedRecoveryAccountOperation(HF26Representation, tag="changed_recovery_account_operation"):
            value: ChangedRecoveryAccountOperation


class LegacyRepresentationChangedRecoveryAccountOperation(LegacyRepresentation, tag="changed_recovery_account", array_like=True):
            value: ChangedRecoveryAccountOperation


class HF26RepresentationClearNullAccountBalanceOperation(HF26Representation, tag="clear_null_account_balance_operation"):
            value: ClearNullAccountBalanceOperation


class LegacyRepresentationClearNullAccountBalanceOperation(LegacyRepresentation, tag="clear_null_account_balance", array_like=True):
            value: ClearNullAccountBalanceOperation


class HF26RepresentationCollateralizedConvertImmediateConversionOperation(HF26Representation, tag="collateralized_convert_immediate_conversion_operation"):
            value: CollateralizedConvertImmediateConversionOperation


class LegacyRepresentationCollateralizedConvertImmediateConversionOperation(LegacyRepresentation, tag="collateralized_convert_immediate_conversion", array_like=True):
            value: CollateralizedConvertImmediateConversionOperation


class HF26RepresentationCommentBenefactorRewardOperation(HF26Representation, tag="comment_benefactor_reward_operation"):
            value: CommentBenefactorRewardOperation


class LegacyRepresentationCommentBenefactorRewardOperation(LegacyRepresentation, tag="comment_benefactor_reward", array_like=True):
            value: CommentBenefactorRewardOperation


class HF26RepresentationCommentPayoutUpdateOperation(HF26Representation, tag="comment_payout_update_operation"):
            value: CommentPayoutUpdateOperation


class LegacyRepresentationCommentPayoutUpdateOperation(LegacyRepresentation, tag="comment_payout_update", array_like=True):
            value: CommentPayoutUpdateOperation


class HF26RepresentationCommentRewardOperation(HF26Representation, tag="comment_reward_operation"):
            value: CommentRewardOperation


class LegacyRepresentationCommentRewardOperation(LegacyRepresentation, tag="comment_reward", array_like=True):
            value: CommentRewardOperation


class HF26RepresentationConsolidateTreasuryBalanceOperation(HF26Representation, tag="consolidate_treasury_balance_operation"):
            value: ConsolidateTreasuryBalanceOperation


class LegacyRepresentationConsolidateTreasuryBalanceOperation(LegacyRepresentation, tag="consolidate_treasury_balance", array_like=True):
            value: ConsolidateTreasuryBalanceOperation


class HF26RepresentationCurationRewardOperation(HF26Representation, tag="curation_reward_operation"):
            value: CurationRewardOperation


class LegacyRepresentationCurationRewardOperation(LegacyRepresentation, tag="curation_reward", array_like=True):
            value: CurationRewardOperation


class HF26RepresentationDeclinedVotingRightsOperation(HF26Representation, tag="declined_voting_rights_operation"):
            value: DeclinedVotingRightsOperation


class LegacyRepresentationDeclinedVotingRightsOperation(LegacyRepresentation, tag="declined_voting_rights", array_like=True):
            value: DeclinedVotingRightsOperation


class HF26RepresentationDelayedVotingOperation(HF26Representation, tag="delayed_voting_operation"):
            value: DelayedVotingOperation


class LegacyRepresentationDelayedVotingOperation(LegacyRepresentation, tag="delayed_voting", array_like=True):
            value: DelayedVotingOperation


class HF26RepresentationDhfConversionOperation(HF26Representation, tag="dhf_conversion_operation"):
            value: DhfConversionOperation


class LegacyRepresentationDhfConversionOperation(LegacyRepresentation, tag="dhf_conversion", array_like=True):
            value: DhfConversionOperation


class HF26RepresentationDhfFundingOperation(HF26Representation, tag="dhf_funding_operation"):
            value: DhfFundingOperation


class LegacyRepresentationDhfFundingOperation(LegacyRepresentation, tag="dhf_funding", array_like=True):
            value: DhfFundingOperation


class HF26RepresentationEffectiveCommentVoteOperation(HF26Representation, tag="effective_comment_vote_operation"):
            value: EffectiveCommentVoteOperation


class LegacyRepresentationEffectiveCommentVoteOperation(LegacyRepresentation, tag="effective_comment_vote", array_like=True):
            value: EffectiveCommentVoteOperation


class HF26RepresentationEscrowApprovedOperation(HF26Representation, tag="escrow_approved_operation"):
            value: EscrowApprovedOperation


class LegacyRepresentationEscrowApprovedOperation(LegacyRepresentation, tag="escrow_approved", array_like=True):
            value: EscrowApprovedOperation


class HF26RepresentationEscrowRejectedOperation(HF26Representation, tag="escrow_rejected_operation"):
            value: EscrowRejectedOperation


class LegacyRepresentationEscrowRejectedOperation(LegacyRepresentation, tag="escrow_rejected", array_like=True):
            value: EscrowRejectedOperation


class HF26RepresentationExpiredAccountNotificationOperation(HF26Representation, tag="expired_account_notification_operation"):
            value: ExpiredAccountNotificationOperation


class LegacyRepresentationExpiredAccountNotificationOperation(LegacyRepresentation, tag="expired_account_notification", array_like=True):
            value: ExpiredAccountNotificationOperation


class HF26RepresentationFailedRecurrentTransferOperation(HF26Representation, tag="failed_recurrent_transfer_operation"):
            value: FailedRecurrentTransferOperation


class LegacyRepresentationFailedRecurrentTransferOperation(LegacyRepresentation, tag="failed_recurrent_transfer", array_like=True):
            value: FailedRecurrentTransferOperation


class HF26RepresentationFillCollateralizedConvertRequestOperation(HF26Representation, tag="fill_collateralized_convert_request_operation"):
            value: FillCollateralizedConvertRequestOperation


class LegacyRepresentationFillCollateralizedConvertRequestOperation(LegacyRepresentation, tag="fill_collateralized_convert_request", array_like=True):
            value: FillCollateralizedConvertRequestOperation


class HF26RepresentationFillConvertRequestOperation(HF26Representation, tag="fill_convert_request_operation"):
            value: FillConvertRequestOperation


class LegacyRepresentationFillConvertRequestOperation(LegacyRepresentation, tag="fill_convert_request", array_like=True):
            value: FillConvertRequestOperation


class HF26RepresentationFillOrderOperation(HF26Representation, tag="fill_order_operation"):
            value: FillOrderOperation


class LegacyRepresentationFillOrderOperation(LegacyRepresentation, tag="fill_order", array_like=True):
            value: FillOrderOperation


class HF26RepresentationFillRecurrentTransferOperation(HF26Representation, tag="fill_recurrent_transfer_operation"):
            value: FillRecurrentTransferOperation


class LegacyRepresentationFillRecurrentTransferOperation(LegacyRepresentation, tag="fill_recurrent_transfer", array_like=True):
            value: FillRecurrentTransferOperation


class HF26RepresentationFillTransferFromSavingsOperation(HF26Representation, tag="fill_transfer_from_savings_operation"):
            value: FillTransferFromSavingsOperation


class LegacyRepresentationFillTransferFromSavingsOperation(LegacyRepresentation, tag="fill_transfer_from_savings", array_like=True):
            value: FillTransferFromSavingsOperation


class HF26RepresentationFillVestingWithdrawOperation(HF26Representation, tag="fill_vesting_withdraw_operation"):
            value: FillVestingWithdrawOperation


class LegacyRepresentationFillVestingWithdrawOperation(LegacyRepresentation, tag="fill_vesting_withdraw", array_like=True):
            value: FillVestingWithdrawOperation


class HF26RepresentationHardforkHiveOperation(HF26Representation, tag="hardfork_hive_operation"):
            value: HardforkHiveOperation


class LegacyRepresentationHardforkHiveOperation(LegacyRepresentation, tag="hardfork_hive", array_like=True):
            value: HardforkHiveOperation


class HF26RepresentationHardforkHiveRestoreOperation(HF26Representation, tag="hardfork_hive_restore_operation"):
            value: HardforkHiveRestoreOperation


class LegacyRepresentationHardforkHiveRestoreOperation(LegacyRepresentation, tag="hardfork_hive_restore", array_like=True):
            value: HardforkHiveRestoreOperation


class HF26RepresentationHardforkOperation(HF26Representation, tag="hardfork_operation"):
            value: HardforkOperation


class LegacyRepresentationHardforkOperation(LegacyRepresentation, tag="hardfork", array_like=True):
            value: HardforkOperation


class HF26RepresentationIneffectiveDeleteCommentOperation(HF26Representation, tag="ineffective_delete_comment_operation"):
            value: IneffectiveDeleteCommentOperation


class LegacyRepresentationIneffectiveDeleteCommentOperation(LegacyRepresentation, tag="ineffective_delete_comment", array_like=True):
            value: IneffectiveDeleteCommentOperation


class HF26RepresentationInterestOperation(HF26Representation, tag="interest_operation"):
            value: InterestOperation


class LegacyRepresentationInterestOperation(LegacyRepresentation, tag="interest", array_like=True):
            value: InterestOperation


class HF26RepresentationLimitOrderCancelledOperation(HF26Representation, tag="limit_order_cancelled_operation"):
            value: LimitOrderCancelledOperation


class LegacyRepresentationLimitOrderCancelledOperation(LegacyRepresentation, tag="limit_order_cancelled", array_like=True):
            value: LimitOrderCancelledOperation


class HF26RepresentationLiquidityRewardOperation(HF26Representation, tag="liquidity_reward_operation"):
            value: LiquidityRewardOperation


class LegacyRepresentationLiquidityRewardOperation(LegacyRepresentation, tag="liquidity_reward", array_like=True):
            value: LiquidityRewardOperation


class HF26RepresentationPowRewardOperation(HF26Representation, tag="pow_reward_operation"):
            value: PowRewardOperation


class LegacyRepresentationPowRewardOperation(LegacyRepresentation, tag="pow_reward", array_like=True):
            value: PowRewardOperation


class HF26RepresentationProducerMissedOperation(HF26Representation, tag="producer_missed_operation"):
            value: ProducerMissedOperation


class LegacyRepresentationProducerMissedOperation(LegacyRepresentation, tag="producer_missed", array_like=True):
            value: ProducerMissedOperation


class HF26RepresentationProducerRewardOperation(HF26Representation, tag="producer_reward_operation"):
            value: ProducerRewardOperation


class LegacyRepresentationProducerRewardOperation(LegacyRepresentation, tag="producer_reward", array_like=True):
            value: ProducerRewardOperation


class HF26RepresentationProposalFeeOperation(HF26Representation, tag="proposal_fee_operation"):
            value: ProposalFeeOperation


class LegacyRepresentationProposalFeeOperation(LegacyRepresentation, tag="proposal_fee", array_like=True):
            value: ProposalFeeOperation


class HF26RepresentationProposalPayOperation(HF26Representation, tag="proposal_pay_operation"):
            value: ProposalPayOperation


class LegacyRepresentationProposalPayOperation(LegacyRepresentation, tag="proposal_pay", array_like=True):
            value: ProposalPayOperation


class HF26RepresentationProxyClearedOperation(HF26Representation, tag="proxy_cleared_operation"):
            value: ProxyClearedOperation


class LegacyRepresentationProxyClearedOperation(LegacyRepresentation, tag="proxy_cleared", array_like=True):
            value: ProxyClearedOperation


class HF26RepresentationReturnVestingDelegationOperation(HF26Representation, tag="return_vesting_delegation_operation"):
            value: ReturnVestingDelegationOperation


class LegacyRepresentationReturnVestingDelegationOperation(LegacyRepresentation, tag="return_vesting_delegation", array_like=True):
            value: ReturnVestingDelegationOperation


class HF26RepresentationShutDownWitnessOperation(HF26Representation, tag="shut_down_witness_operation"):
            value: ShutDownWitnessOperation


class LegacyRepresentationShutDownWitnessOperation(LegacyRepresentation, tag="shut_down_witness", array_like=True):
            value: ShutDownWitnessOperation


class HF26RepresentationSystemWarningOperation(HF26Representation, tag="system_warning_operation"):
            value: SystemWarningOperation


class LegacyRepresentationSystemWarningOperation(LegacyRepresentation, tag="system_warning", array_like=True):
            value: SystemWarningOperation


class HF26RepresentationTransferToVestingCompletedOperation(HF26Representation, tag="transfer_to_vesting_completed_operation"):
            value: TransferToVestingCompletedOperation


class LegacyRepresentationTransferToVestingCompletedOperation(LegacyRepresentation, tag="transfer_to_vesting_completed", array_like=True):
            value: TransferToVestingCompletedOperation


class HF26RepresentationVestingSharesSplitOperation(HF26Representation, tag="vesting_shares_split_operation"):
            value: VestingSharesSplitOperation


class LegacyRepresentationVestingSharesSplitOperation(LegacyRepresentation, tag="vesting_shares_split", array_like=True):
            value: VestingSharesSplitOperation
