# fmt: off

# WARNING: This code was automatically generated by a script.
# DO NOT EDIT this file manually, as any changes may be overwritten.
# If modifications are needed, please update the generating script instead.

from __future__ import annotations

from typing import Literal, overload

import msgspec

from schemas.operation import Operation
from schemas.operations.virtual.account_created_operation import AccountCreatedOperation
from schemas.operations.virtual.author_reward_operation import AuthorRewardOperation
from schemas.operations.virtual.changed_recovery_account_operation import ChangedRecoveryAccountOperation
from schemas.operations.virtual.clear_null_account_balance_operation import ClearNullAccountBalanceOperation
from schemas.operations.virtual.collateralized_convert_immediate_conversion_operation import (
    CollateralizedConvertImmediateConversionOperation,
)
from schemas.operations.virtual.comment_benefactor_reward_operation import CommentBenefactorRewardOperation
from schemas.operations.virtual.comment_payout_update_operation import CommentPayoutUpdateOperation
from schemas.operations.virtual.comment_reward_operation import CommentRewardOperation
from schemas.operations.virtual.consolidate_treasury_balance_operation import ConsolidateTreasuryBalanceOperation
from schemas.operations.virtual.curation_reward_operation import CurationRewardOperation
from schemas.operations.virtual.declined_voting_rights_operation import DeclinedVotingRightsOperation
from schemas.operations.virtual.delayed_voting_operation import DelayedVotingOperation
from schemas.operations.virtual.dhf_conversion_operation import DhfConversionOperation
from schemas.operations.virtual.dhf_funding_operation import DhfFundingOperation
from schemas.operations.virtual.effective_comment_vote_operation import EffectiveCommentVoteOperation
from schemas.operations.virtual.escrow_approved_operation import EscrowApprovedOperation
from schemas.operations.virtual.escrow_rejected_operation import EscrowRejectedOperation
from schemas.operations.virtual.expired_account_notification_operation import ExpiredAccountNotificationOperation
from schemas.operations.virtual.failed_recurrent_transfer_operation import FailedRecurrentTransferOperation
from schemas.operations.virtual.fill_collateralized_convert_request_operation import (
    FillCollateralizedConvertRequestOperation,
)
from schemas.operations.virtual.fill_convert_request_operation import FillConvertRequestOperation
from schemas.operations.virtual.fill_order_operation import FillOrderOperation
from schemas.operations.virtual.fill_recurrent_transfer_operation import FillRecurrentTransferOperation
from schemas.operations.virtual.fill_transfer_from_savings_operation import FillTransferFromSavingsOperation
from schemas.operations.virtual.fill_vesting_withdraw_operation import FillVestingWithdrawOperation
from schemas.operations.virtual.hardfork_hive_operation import HardforkHiveOperation
from schemas.operations.virtual.hardfork_hive_restore_operation import HardforkHiveRestoreOperation
from schemas.operations.virtual.hardfork_operation import HardforkOperation
from schemas.operations.virtual.ineffective_delete_comment_operation import IneffectiveDeleteCommentOperation
from schemas.operations.virtual.interest_operation import InterestOperation
from schemas.operations.virtual.limit_order_cancelled_operation import LimitOrderCancelledOperation
from schemas.operations.virtual.liquidity_reward_operation import LiquidityRewardOperation
from schemas.operations.virtual.pow_reward_operation import PowRewardOperation
from schemas.operations.virtual.producer_missed_operation import ProducerMissedOperation
from schemas.operations.virtual.producer_reward_operation import ProducerRewardOperation
from schemas.operations.virtual.proposal_fee_operation import ProposalFeeOperation
from schemas.operations.virtual.proposal_pay_operation import ProposalPayOperation
from schemas.operations.virtual.proxy_cleared_operation import ProxyClearedOperation
from schemas.operations.virtual.return_vesting_delegation_operation import ReturnVestingDelegationOperation
from schemas.operations.virtual.shutdown_witness_operation import ShutDownWitnessOperation
from schemas.operations.virtual.system_warning_operation import SystemWarningOperation
from schemas.operations.virtual.transfer_to_vesting_completed_operation import TransferToVestingCompletedOperation
from schemas.operations.virtual.vesting_shares_split_operation import VestingSharesSplitOperation


class HF26Representation(msgspec.Struct):
    value: Operation

    @property
    def type_(self) -> str:
        return self.value.get_name_with_suffix()


class LegacyRepresentation(msgspec.Struct):
    value: Operation

    @property
    def type_(self) -> str:
        return self.value.get_name()

    @overload
    def __getitem__(self, idx: Literal[0]) -> str: ...
    @overload
    def __getitem__(self, idx: Literal[1]) -> Operation: ...

    def __getitem__(self, idx: Literal[0, 1]) -> str | Operation:
        if idx == 0:
            return self.type_
        if idx == 1:
            return self.value
        raise ValueError("Index out of bound <0; 1>")

class HF26RepresentationAccountCreatedOperation(HF26Representation, tag=AccountCreatedOperation.get_name_with_suffix()):
            value: AccountCreatedOperation


class LegacyRepresentationAccountCreatedOperation(LegacyRepresentation, tag=AccountCreatedOperation.get_name(), array_like=True):
            value: AccountCreatedOperation


class HF26RepresentationAuthorRewardOperation(HF26Representation, tag=AuthorRewardOperation.get_name_with_suffix()):
            value: AuthorRewardOperation


class LegacyRepresentationAuthorRewardOperation(LegacyRepresentation, tag=AuthorRewardOperation.get_name(), array_like=True):
            value: AuthorRewardOperation


class HF26RepresentationChangedRecoveryAccountOperation(HF26Representation, tag=ChangedRecoveryAccountOperation.get_name_with_suffix()):
            value: ChangedRecoveryAccountOperation


class LegacyRepresentationChangedRecoveryAccountOperation(LegacyRepresentation, tag=ChangedRecoveryAccountOperation.get_name(), array_like=True):
            value: ChangedRecoveryAccountOperation


class HF26RepresentationClearNullAccountBalanceOperation(HF26Representation, tag=ClearNullAccountBalanceOperation.get_name_with_suffix()):
            value: ClearNullAccountBalanceOperation


class LegacyRepresentationClearNullAccountBalanceOperation(LegacyRepresentation, tag=ClearNullAccountBalanceOperation.get_name(), array_like=True):
            value: ClearNullAccountBalanceOperation


class HF26RepresentationCollateralizedConvertImmediateConversionOperation(HF26Representation, tag=CollateralizedConvertImmediateConversionOperation.get_name_with_suffix()):
            value: CollateralizedConvertImmediateConversionOperation


class LegacyRepresentationCollateralizedConvertImmediateConversionOperation(LegacyRepresentation, tag=CollateralizedConvertImmediateConversionOperation.get_name(), array_like=True):
            value: CollateralizedConvertImmediateConversionOperation


class HF26RepresentationCommentBenefactorRewardOperation(HF26Representation, tag=CommentBenefactorRewardOperation.get_name_with_suffix()):
            value: CommentBenefactorRewardOperation


class LegacyRepresentationCommentBenefactorRewardOperation(LegacyRepresentation, tag=CommentBenefactorRewardOperation.get_name(), array_like=True):
            value: CommentBenefactorRewardOperation


class HF26RepresentationCommentPayoutUpdateOperation(HF26Representation, tag=CommentPayoutUpdateOperation.get_name_with_suffix()):
            value: CommentPayoutUpdateOperation


class LegacyRepresentationCommentPayoutUpdateOperation(LegacyRepresentation, tag=CommentPayoutUpdateOperation.get_name(), array_like=True):
            value: CommentPayoutUpdateOperation


class HF26RepresentationCommentRewardOperation(HF26Representation, tag=CommentRewardOperation.get_name_with_suffix()):
            value: CommentRewardOperation


class LegacyRepresentationCommentRewardOperation(LegacyRepresentation, tag=CommentRewardOperation.get_name(), array_like=True):
            value: CommentRewardOperation


class HF26RepresentationConsolidateTreasuryBalanceOperation(HF26Representation, tag=ConsolidateTreasuryBalanceOperation.get_name_with_suffix()):
            value: ConsolidateTreasuryBalanceOperation


class LegacyRepresentationConsolidateTreasuryBalanceOperation(LegacyRepresentation, tag=ConsolidateTreasuryBalanceOperation.get_name(), array_like=True):
            value: ConsolidateTreasuryBalanceOperation


class HF26RepresentationCurationRewardOperation(HF26Representation, tag=CurationRewardOperation.get_name_with_suffix()):
            value: CurationRewardOperation


class LegacyRepresentationCurationRewardOperation(LegacyRepresentation, tag=CurationRewardOperation.get_name(), array_like=True):
            value: CurationRewardOperation


class HF26RepresentationDeclinedVotingRightsOperation(HF26Representation, tag=DeclinedVotingRightsOperation.get_name_with_suffix()):
            value: DeclinedVotingRightsOperation


class LegacyRepresentationDeclinedVotingRightsOperation(LegacyRepresentation, tag=DeclinedVotingRightsOperation.get_name(), array_like=True):
            value: DeclinedVotingRightsOperation


class HF26RepresentationDelayedVotingOperation(HF26Representation, tag=DelayedVotingOperation.get_name_with_suffix()):
            value: DelayedVotingOperation


class LegacyRepresentationDelayedVotingOperation(LegacyRepresentation, tag=DelayedVotingOperation.get_name(), array_like=True):
            value: DelayedVotingOperation


class HF26RepresentationDhfConversionOperation(HF26Representation, tag=DhfConversionOperation.get_name_with_suffix()):
            value: DhfConversionOperation


class LegacyRepresentationDhfConversionOperation(LegacyRepresentation, tag=DhfConversionOperation.get_name(), array_like=True):
            value: DhfConversionOperation


class HF26RepresentationDhfFundingOperation(HF26Representation, tag=DhfFundingOperation.get_name_with_suffix()):
            value: DhfFundingOperation


class LegacyRepresentationDhfFundingOperation(LegacyRepresentation, tag=DhfFundingOperation.get_name(), array_like=True):
            value: DhfFundingOperation


class HF26RepresentationEffectiveCommentVoteOperation(HF26Representation, tag=EffectiveCommentVoteOperation.get_name_with_suffix()):
            value: EffectiveCommentVoteOperation


class LegacyRepresentationEffectiveCommentVoteOperation(LegacyRepresentation, tag=EffectiveCommentVoteOperation.get_name(), array_like=True):
            value: EffectiveCommentVoteOperation


class HF26RepresentationEscrowApprovedOperation(HF26Representation, tag=EscrowApprovedOperation.get_name_with_suffix()):
            value: EscrowApprovedOperation


class LegacyRepresentationEscrowApprovedOperation(LegacyRepresentation, tag=EscrowApprovedOperation.get_name(), array_like=True):
            value: EscrowApprovedOperation


class HF26RepresentationEscrowRejectedOperation(HF26Representation, tag=EscrowRejectedOperation.get_name_with_suffix()):
            value: EscrowRejectedOperation


class LegacyRepresentationEscrowRejectedOperation(LegacyRepresentation, tag=EscrowRejectedOperation.get_name(), array_like=True):
            value: EscrowRejectedOperation


class HF26RepresentationExpiredAccountNotificationOperation(HF26Representation, tag=ExpiredAccountNotificationOperation.get_name_with_suffix()):
            value: ExpiredAccountNotificationOperation


class LegacyRepresentationExpiredAccountNotificationOperation(LegacyRepresentation, tag=ExpiredAccountNotificationOperation.get_name(), array_like=True):
            value: ExpiredAccountNotificationOperation


class HF26RepresentationFailedRecurrentTransferOperation(HF26Representation, tag=FailedRecurrentTransferOperation.get_name_with_suffix()):
            value: FailedRecurrentTransferOperation


class LegacyRepresentationFailedRecurrentTransferOperation(LegacyRepresentation, tag=FailedRecurrentTransferOperation.get_name(), array_like=True):
            value: FailedRecurrentTransferOperation


class HF26RepresentationFillCollateralizedConvertRequestOperation(HF26Representation, tag=FillCollateralizedConvertRequestOperation.get_name_with_suffix()):
            value: FillCollateralizedConvertRequestOperation


class LegacyRepresentationFillCollateralizedConvertRequestOperation(LegacyRepresentation, tag=FillCollateralizedConvertRequestOperation.get_name(), array_like=True):
            value: FillCollateralizedConvertRequestOperation


class HF26RepresentationFillConvertRequestOperation(HF26Representation, tag=FillConvertRequestOperation.get_name_with_suffix()):
            value: FillConvertRequestOperation


class LegacyRepresentationFillConvertRequestOperation(LegacyRepresentation, tag=FillConvertRequestOperation.get_name(), array_like=True):
            value: FillConvertRequestOperation


class HF26RepresentationFillOrderOperation(HF26Representation, tag=FillOrderOperation.get_name_with_suffix()):
            value: FillOrderOperation


class LegacyRepresentationFillOrderOperation(LegacyRepresentation, tag=FillOrderOperation.get_name(), array_like=True):
            value: FillOrderOperation


class HF26RepresentationFillRecurrentTransferOperation(HF26Representation, tag=FillRecurrentTransferOperation.get_name_with_suffix()):
            value: FillRecurrentTransferOperation


class LegacyRepresentationFillRecurrentTransferOperation(LegacyRepresentation, tag=FillRecurrentTransferOperation.get_name(), array_like=True):
            value: FillRecurrentTransferOperation


class HF26RepresentationFillTransferFromSavingsOperation(HF26Representation, tag=FillTransferFromSavingsOperation.get_name_with_suffix()):
            value: FillTransferFromSavingsOperation


class LegacyRepresentationFillTransferFromSavingsOperation(LegacyRepresentation, tag=FillTransferFromSavingsOperation.get_name(), array_like=True):
            value: FillTransferFromSavingsOperation


class HF26RepresentationFillVestingWithdrawOperation(HF26Representation, tag=FillVestingWithdrawOperation.get_name_with_suffix()):
            value: FillVestingWithdrawOperation


class LegacyRepresentationFillVestingWithdrawOperation(LegacyRepresentation, tag=FillVestingWithdrawOperation.get_name(), array_like=True):
            value: FillVestingWithdrawOperation


class HF26RepresentationHardforkHiveOperation(HF26Representation, tag=HardforkHiveOperation.get_name_with_suffix()):
            value: HardforkHiveOperation


class LegacyRepresentationHardforkHiveOperation(LegacyRepresentation, tag=HardforkHiveOperation.get_name(), array_like=True):
            value: HardforkHiveOperation


class HF26RepresentationHardforkHiveRestoreOperation(HF26Representation, tag=HardforkHiveRestoreOperation.get_name_with_suffix()):
            value: HardforkHiveRestoreOperation


class LegacyRepresentationHardforkHiveRestoreOperation(LegacyRepresentation, tag=HardforkHiveRestoreOperation.get_name(), array_like=True):
            value: HardforkHiveRestoreOperation


class HF26RepresentationHardforkOperation(HF26Representation, tag=HardforkOperation.get_name_with_suffix()):
            value: HardforkOperation


class LegacyRepresentationHardforkOperation(LegacyRepresentation, tag=HardforkOperation.get_name(), array_like=True):
            value: HardforkOperation


class HF26RepresentationIneffectiveDeleteCommentOperation(HF26Representation, tag=IneffectiveDeleteCommentOperation.get_name_with_suffix()):
            value: IneffectiveDeleteCommentOperation


class LegacyRepresentationIneffectiveDeleteCommentOperation(LegacyRepresentation, tag=IneffectiveDeleteCommentOperation.get_name(), array_like=True):
            value: IneffectiveDeleteCommentOperation


class HF26RepresentationInterestOperation(HF26Representation, tag=InterestOperation.get_name_with_suffix()):
            value: InterestOperation


class LegacyRepresentationInterestOperation(LegacyRepresentation, tag=InterestOperation.get_name(), array_like=True):
            value: InterestOperation


class HF26RepresentationLimitOrderCancelledOperation(HF26Representation, tag=LimitOrderCancelledOperation.get_name_with_suffix()):
            value: LimitOrderCancelledOperation


class LegacyRepresentationLimitOrderCancelledOperation(LegacyRepresentation, tag=LimitOrderCancelledOperation.get_name(), array_like=True):
            value: LimitOrderCancelledOperation


class HF26RepresentationLiquidityRewardOperation(HF26Representation, tag=LiquidityRewardOperation.get_name_with_suffix()):
            value: LiquidityRewardOperation


class LegacyRepresentationLiquidityRewardOperation(LegacyRepresentation, tag=LiquidityRewardOperation.get_name(), array_like=True):
            value: LiquidityRewardOperation


class HF26RepresentationPowRewardOperation(HF26Representation, tag=PowRewardOperation.get_name_with_suffix()):
            value: PowRewardOperation


class LegacyRepresentationPowRewardOperation(LegacyRepresentation, tag=PowRewardOperation.get_name(), array_like=True):
            value: PowRewardOperation


class HF26RepresentationProducerMissedOperation(HF26Representation, tag=ProducerMissedOperation.get_name_with_suffix()):
            value: ProducerMissedOperation


class LegacyRepresentationProducerMissedOperation(LegacyRepresentation, tag=ProducerMissedOperation.get_name(), array_like=True):
            value: ProducerMissedOperation


class HF26RepresentationProducerRewardOperation(HF26Representation, tag=ProducerRewardOperation.get_name_with_suffix()):
            value: ProducerRewardOperation


class LegacyRepresentationProducerRewardOperation(LegacyRepresentation, tag=ProducerRewardOperation.get_name(), array_like=True):
            value: ProducerRewardOperation


class HF26RepresentationProposalFeeOperation(HF26Representation, tag=ProposalFeeOperation.get_name_with_suffix()):
            value: ProposalFeeOperation


class LegacyRepresentationProposalFeeOperation(LegacyRepresentation, tag=ProposalFeeOperation.get_name(), array_like=True):
            value: ProposalFeeOperation


class HF26RepresentationProposalPayOperation(HF26Representation, tag=ProposalPayOperation.get_name_with_suffix()):
            value: ProposalPayOperation


class LegacyRepresentationProposalPayOperation(LegacyRepresentation, tag=ProposalPayOperation.get_name(), array_like=True):
            value: ProposalPayOperation


class HF26RepresentationProxyClearedOperation(HF26Representation, tag=ProxyClearedOperation.get_name_with_suffix()):
            value: ProxyClearedOperation


class LegacyRepresentationProxyClearedOperation(LegacyRepresentation, tag=ProxyClearedOperation.get_name(), array_like=True):
            value: ProxyClearedOperation


class HF26RepresentationReturnVestingDelegationOperation(HF26Representation, tag=ReturnVestingDelegationOperation.get_name_with_suffix()):
            value: ReturnVestingDelegationOperation


class LegacyRepresentationReturnVestingDelegationOperation(LegacyRepresentation, tag=ReturnVestingDelegationOperation.get_name(), array_like=True):
            value: ReturnVestingDelegationOperation


class HF26RepresentationShutDownWitnessOperation(HF26Representation, tag=ShutDownWitnessOperation.get_name_with_suffix()):
            value: ShutDownWitnessOperation


class LegacyRepresentationShutDownWitnessOperation(LegacyRepresentation, tag=ShutDownWitnessOperation.get_name(), array_like=True):
            value: ShutDownWitnessOperation


class HF26RepresentationSystemWarningOperation(HF26Representation, tag=SystemWarningOperation.get_name_with_suffix()):
            value: SystemWarningOperation


class LegacyRepresentationSystemWarningOperation(LegacyRepresentation, tag=SystemWarningOperation.get_name(), array_like=True):
            value: SystemWarningOperation


class HF26RepresentationTransferToVestingCompletedOperation(HF26Representation, tag=TransferToVestingCompletedOperation.get_name_with_suffix()):
            value: TransferToVestingCompletedOperation


class LegacyRepresentationTransferToVestingCompletedOperation(LegacyRepresentation, tag=TransferToVestingCompletedOperation.get_name(), array_like=True):
            value: TransferToVestingCompletedOperation


class HF26RepresentationVestingSharesSplitOperation(HF26Representation, tag=VestingSharesSplitOperation.get_name_with_suffix()):
            value: VestingSharesSplitOperation


class LegacyRepresentationVestingSharesSplitOperation(LegacyRepresentation, tag=VestingSharesSplitOperation.get_name(), array_like=True):
            value: VestingSharesSplitOperation
