from __future__ import annotations

from typing import Any

import pytest

from schemas.__private.hive_factory import HiveResult
from schemas.database_api import (
    FindDeclineVotingRightsRequests,
    FindLimitOrders,
    FindProposals,
    FindVestingDelegationExpirations,
    FindVestingDelegations,
    GetActiveWitnesses,
    GetConfig,
    GetDynamicGlobalProperties,
    GetFeedHistory,
    GetHardforkProperties,
    GetOrderBook,
    GetPotentialSignatures,
    GetRequiredSignatures,
    GetRewardFunds,
    GetTransactionHex,
    GetVersion,
    GetWitnessSchedule,
    ListAccountRecoveryRequests,
    ListAccounts,
    ListChangeRecoveryAccountRequests,
    ListComments,
    ListDeclineVotingRightsRequests,
    ListEscrows,
    ListHbdConversionRequests,
    ListLimitOrders,
    ListOwnerHistories,
    ListProposalVotes,
    ListSavingsWithdrawals,
    ListVestingDelegationExpirations,
    ListVestingDelegations,
    ListWithdrawVestingRoutes,
    ListWitnesses,
    ListWitnessVotes,
)
from tests.test_database_api.reponses_from_api import (
    FIND_DECLINE_VOTING_RIGHTS_REQUESTS,
    FIND_LIMIT_ORDERS,
    FIND_PROPOSALS,
    FIND_VESTING_DELEGATION_EXPIRATIONS,
    FIND_VESTING_DELEGATIONS,
    GET_ACTIVE_WITNESSES,
    GET_CONFIG,
    GET_DYNAMIC_GLOBAL_PROPERTIES,
    GET_FEED_HISTORY,
    GET_HARDFORK_PROPERTIES,
    GET_ORDER_BOOK,
    GET_POTENTIAL_SIGNATURES,
    GET_REQUIRED_SIGNATURES,
    GET_REWARD_FUNDS,
    GET_TRANSACTION_HEX,
    GET_VERSION,
    GET_WITNESS_SCHEDULE,
    LIST_ACCOUNT_RECOVERY_REQUESTS,
    LIST_ACCOUNTS,
    LIST_CHANGE_RECOVERY_ACCOUNT_REQUESTS,
    LIST_COMMENTS,
    LIST_DECLINE_VOTING_RIGHTS_REQUESTS,
    LIST_ESCROWS,
    LIST_HBD_CONVERSION_REQUESTS,
    LIST_LIMIT_ORDERS,
    LIST_OWNER_HISTORIES,
    LIST_PROPOSAL_VOTES,
    LIST_SAVINGS_WITHDRAWALS,
    LIST_VESTING_DELEGATION_EXPIRATIONS,
    LIST_VESTING_DELEGATIONS,
    LIST_WITHDRAW_VESTING_ROUTES,
    LIST_WITNESS_VOTES,
    LIST_WITNESSES,
)


@pytest.mark.parametrize(
    "parameter, schema",
    [
        (FIND_PROPOSALS, FindProposals),
        (LIST_ESCROWS, ListEscrows),
        (LIST_COMMENTS, ListComments),
        (LIST_OWNER_HISTORIES, ListOwnerHistories),
        (LIST_WITNESSES, ListWitnesses),
        (LIST_WITHDRAW_VESTING_ROUTES, ListWithdrawVestingRoutes),
        (LIST_DECLINE_VOTING_RIGHTS_REQUESTS, ListDeclineVotingRightsRequests),
        (FIND_VESTING_DELEGATIONS, FindVestingDelegations),
        (LIST_ACCOUNTS, ListAccounts),
        (LIST_CHANGE_RECOVERY_ACCOUNT_REQUESTS, ListChangeRecoveryAccountRequests),
        (LIST_ACCOUNT_RECOVERY_REQUESTS, ListAccountRecoveryRequests),
        (LIST_VESTING_DELEGATION_EXPIRATIONS, ListVestingDelegationExpirations),
        (LIST_HBD_CONVERSION_REQUESTS, ListHbdConversionRequests),
        (LIST_SAVINGS_WITHDRAWALS, ListSavingsWithdrawals),
        (LIST_LIMIT_ORDERS, ListLimitOrders),
        (LIST_WITNESS_VOTES, ListWitnessVotes),
        (LIST_PROPOSAL_VOTES, ListProposalVotes),
        (LIST_VESTING_DELEGATIONS, ListVestingDelegations),
        (FIND_LIMIT_ORDERS, FindLimitOrders),
        (GET_DYNAMIC_GLOBAL_PROPERTIES, GetDynamicGlobalProperties),
        (GET_CONFIG, GetConfig),
        (GET_POTENTIAL_SIGNATURES, GetPotentialSignatures),
        (GET_WITNESS_SCHEDULE, GetWitnessSchedule),
        (FIND_DECLINE_VOTING_RIGHTS_REQUESTS, FindDeclineVotingRightsRequests),
        (FIND_VESTING_DELEGATION_EXPIRATIONS, FindVestingDelegationExpirations),
        (GET_REQUIRED_SIGNATURES, GetRequiredSignatures),
        (GET_VERSION, GetVersion),
        (GET_ORDER_BOOK, GetOrderBook),
        (GET_FEED_HISTORY, GetFeedHistory),
        (GET_REWARD_FUNDS, GetRewardFunds),
        (GET_ACTIVE_WITNESSES, GetActiveWitnesses),
        (GET_TRANSACTION_HEX, GetTransactionHex),
        (GET_HARDFORK_PROPERTIES, GetHardforkProperties),
    ],
)
def test_schemas_of_database_api_responses(parameter: dict[str, Any], schema: Any) -> None:
    HiveResult[schema](**parameter)
