# fmt: off

# WARNING: This code was automatically generated by a script.
# DO NOT EDIT this file manually, as any changes may be overwritten.
# If modifications are needed, please update the generating script instead.

from __future__ import annotations

from schemas.operations.extensions.comment_options_extensions import CommentPayoutBeneficiaries
from schemas.operations.extensions.recurrent_transfer_extensions import RecurrentTransferPairId
from schemas.operations.extensions.update_proposal_extensions import UpdateProposalEndDate
from schemas.operations.representation_types import HF26Representation


class HF26RepresentationCommentPayoutBeneficiariesOperationExtension(HF26Representation[CommentPayoutBeneficiaries], tag=CommentPayoutBeneficiaries.get_name()):
            value: CommentPayoutBeneficiaries


class HF26RepresentationRecurrentTransferPairIdOperationExtension(HF26Representation[RecurrentTransferPairId], tag=RecurrentTransferPairId.get_name()):
            value: RecurrentTransferPairId


class HF26RepresentationUpdateProposalEndDateOperationExtension(HF26Representation[UpdateProposalEndDate], tag=UpdateProposalEndDate.get_name()):
            value: UpdateProposalEndDate
