# fmt: off

# WARNING: This code was automatically generated by a script.
# DO NOT EDIT this file manually, as any changes may be overwritten.
# If modifications are needed, please update the generating script instead.

from __future__ import annotations

from schemas.operations.extensions.comment_options_extensions import CommentPayoutBeneficiaries
from schemas.operations.extensions.recurrent_transfer_extensions import RecurrentTransferPairId
from schemas.operations.extensions.update_proposal_extensions import UpdateProposalEndDate
from schemas.operations.representation_types import HF26Representation, LegacyRepresentation


class HF26RepresentationCommentPayoutBeneficiariesOperationExtension(HF26Representation[CommentPayoutBeneficiaries], tag=CommentPayoutBeneficiaries.get_name_with_suffix()):
            value: CommentPayoutBeneficiaries


class LegacyRepresentationCommentPayoutBeneficiariesOperationExtension(LegacyRepresentation[CommentPayoutBeneficiaries], tag=CommentPayoutBeneficiaries.get_name(), array_like=True):
            value: CommentPayoutBeneficiaries


class HF26RepresentationRecurrentTransferPairIdOperationExtension(HF26Representation[RecurrentTransferPairId], tag=RecurrentTransferPairId.get_name_with_suffix()):
            value: RecurrentTransferPairId


class LegacyRepresentationRecurrentTransferPairIdOperationExtension(LegacyRepresentation[RecurrentTransferPairId], tag=RecurrentTransferPairId.get_name(), array_like=True):
            value: RecurrentTransferPairId


class HF26RepresentationUpdateProposalEndDateOperationExtension(HF26Representation[UpdateProposalEndDate], tag=UpdateProposalEndDate.get_name_with_suffix()):
            value: UpdateProposalEndDate


class LegacyRepresentationUpdateProposalEndDateOperationExtension(LegacyRepresentation[UpdateProposalEndDate], tag=UpdateProposalEndDate.get_name(), array_like=True):
            value: UpdateProposalEndDate
