import pytest

from schemas.predefined import *
from schemas.predefined import Operation


@pytest.mark.parametrize(
    'operation', [
        #  hive_operation
        'vote_operation',
        'comment_operation',
        'transfer_operation',
        'transfer_to_vesting_operation',
        'withdraw_vesting_operation',
        'limit_order_create_operation',
        'limit_orrder_cancel_operation',
        'feed_publish_operation',
        'convert_operation',
        'account_create_operation',
        'account_update_operation',
        'witness_update_operation',
        'account_witness_vote_operation',
        'account_witness_proxy_operation',
        'pow_operation',
        'custom_operation',
        'report_over_production_operation',
        'delete_comment_operation',
        'custom_json_operation',
        'comment_options_operation',
        'set_withdraw_vesting_route_operation',
        'limit_order_create2_operation',
        'claim_account_operation',
        'create_claimed_account_operation',
        'request_account_recovery_operation',
        'recover_account_operation',
        'change_recovery_account_operation',
        'escrow_transfer_operation',
        'escrow_dispute_operation',
        'escrow_release_operation',
        'pow2_operation',
        'escrow_approve_operation',
        'transfer_to_savings_operation',
        'transfer_from_savings_operation',
        'cancel_transfer_from_savings_operation',
        'custom_binary_operation',
        'decline_voting_rights_operation',
        'reset_account_operation',
        'set_reset_account_operation',
        'claim_reward_balance_operation',
        'delegate_vesting_shares_operation',
        'account_create_with_delegation_operation',
        'witness_set_properties_operation',
        'account_update2_operation',
        'create_proposal_operation',
        'update_proposal_votes_operation',
        'remove_proposal_operation',
        'update_proposal_operation',
        'collateralized_convert_operation',
        'recurrent_transfer_operation',
        # hive_virtual_operation
        'fill_convert_request_operation',
        'author_reward_operation',
        'curation_reward_operation',
        'comment_reward_operation',
        'liquidity_reward_operation',
        'interest_operation',
        'fill_vesting_withdraw_operation',
        'fill_order_operation',
        'shutdown_witness_operation',
        'fill_transfer_from_savings_operation',
        'hardfork_operation',
        'comment_payout_update_operation',
        'return_vesting_delegation_operation',
        'comment_benefactor_reward_operation',
        'producer_reward_operation',
        'clear_null_account_balance_operation',
        'proposal_pay_operation',
        'sps_fund_operation',
        'hardfork_hive_operation',
        'hardfork_hive_restore_operation',
        'delayed_voting_operation',
        'consolidate_treasury_balance_operation',
        'effective_comment_vote_operation',
        'ineffective_delete_comment_operation',
        'sps_convert_operation',
        'expired_account_notification_operation',
        'changed_recovery_account_operation',
        'transfer_to_vesting_completed_operation',
        'pow_reward_operation',
        'vesting_shares_split_operation',
        'account_created_operation',
        'fill_collateralized_convert_request_operation',
        'system_warning_operation',
        'fill_recurrent_transfer_operation',
        'failed_recurrent_transfer_operation',
        'limit_order_cancelled_operation',
        # hive_smt_operation
        'claim_reward_balance2_operation',
        'smt_setup_operation',
        'smt_setup_emissions_operation',
        'smt_set_setup_parameters_operation',
        'smt_set_runtime_parameters_operation',
        'smt_create_operation',
        'smt_contribute_operation',
    ]
)
def test_operations(wallet, operation):
    response = wallet.api.get_prototype_operation(operation)
    print()
    