# fmt: off

# WARNING: This code was automatically generated by a script.
# DO NOT EDIT this file manually, as any changes may be overwritten.
# If modifications are needed, please update the generating script instead.

from __future__ import annotations

from typing import Generic, TypeVar, cast

from schemas.apis import (
    account_by_key_api,
    account_history_api,
    beekeeper_api,
    block_api,
    condenser_api,
    database_api,
    debug_node_api,
    jsonrpc,
    market_history_api,
    network_broadcast_api,
    network_node_api,
    rc_api,
    reputation_api,
    transaction_status_api,
    wallet_bridge_api,
)
from schemas.jsonrpc_constants import JSONRPCBase

__all__ = ("ExpectResultT", "JSONRPCResult", "AllowedModelsAsResultT")


AllowedModelsAsResultT = (
    account_by_key_api.GetKeyReferences
    | account_history_api.EnumVirtualOps
    | account_history_api.GetAccountHistory
    | account_history_api.GetOpsInBlock
    | account_history_api.GetTransaction
    | beekeeper_api.Create
    | beekeeper_api.CreateSession
    | beekeeper_api.DecryptData
    | beekeeper_api.EmptyResponse
    | beekeeper_api.EncryptData
    | beekeeper_api.GetInfo
    | beekeeper_api.GetPublicKeys
    | beekeeper_api.HasMatchingPrivateKey
    | beekeeper_api.ImportKey
    | beekeeper_api.ImportKeys
    | beekeeper_api.ListKeys
    | beekeeper_api.ListWallets
    | beekeeper_api.SignDigest
    | beekeeper_api.SignTransaction
    | block_api.GetBlock
    | block_api.GetBlockHeader
    | block_api.GetBlockRange
    | condenser_api.BroadcastTransaction
    | condenser_api.BroadcastTransactionSynchronous
    | condenser_api.FindProposals
    | condenser_api.FindRcAccounts
    | condenser_api.FindRecurrentTransfers
    | condenser_api.GetAccountCount
    | condenser_api.GetAccountHistory
    | condenser_api.GetAccountReputations
    | condenser_api.GetAccounts
    | condenser_api.GetActiveVotes
    | condenser_api.GetActiveWitnesses
    | condenser_api.GetBlock
    | condenser_api.GetBlockHeader
    | condenser_api.GetBlog
    | condenser_api.GetBlogEntries
    | condenser_api.GetChainProperties
    | condenser_api.GetCollateralizedConversionRequests
    | condenser_api.GetCommentDiscussionsByPayout
    | condenser_api.GetConfig
    | condenser_api.GetContent
    | condenser_api.GetContentReplies
    | condenser_api.GetConversionRequests
    | condenser_api.GetCurrentMedianHistoryPrice
    | condenser_api.GetDiscussionsByActive
    | condenser_api.GetDiscussionsByAuthorBeforeDate
    | condenser_api.GetDiscussionsByBlog
    | condenser_api.GetDiscussionsByCashout
    | condenser_api.GetDiscussionsByChildren
    | condenser_api.GetDiscussionsByComments
    | condenser_api.GetDiscussionsByCreated
    | condenser_api.GetDiscussionsByFeed
    | condenser_api.GetDiscussionsByHot
    | condenser_api.GetDiscussionsByPromoted
    | condenser_api.GetDiscussionsByTrending
    | condenser_api.GetDiscussionsByVotes
    | condenser_api.GetDynamicGlobalProperties
    | condenser_api.GetEscrow
    | condenser_api.GetExpiringVestingDelegation
    | condenser_api.GetExpiringVestingDelegations
    | condenser_api.GetFeed
    | condenser_api.GetFeedEntries
    | condenser_api.GetFeedHistory
    | condenser_api.GetFollowCount
    | condenser_api.GetFollowers
    | condenser_api.GetFollowing
    | condenser_api.GetHardforkVersion
    | condenser_api.GetKeyReferences
    | condenser_api.GetMarketHistory
    | condenser_api.GetMarketHistoryBuckets
    | condenser_api.GetNextScheduledHardfork
    | condenser_api.GetOpenOrders
    | condenser_api.GetOpsInBlock
    | condenser_api.GetOrderBook
    | condenser_api.GetOwnerHistory
    | condenser_api.GetPostDiscussionsByPayout
    | condenser_api.GetPotentialSignatures
    | condenser_api.GetRebloggedBy
    | condenser_api.GetRecentTrades
    | condenser_api.GetRecoveryRequest
    | condenser_api.GetRepliesByLastUpdate
    | condenser_api.GetRequiredSignatures
    | condenser_api.GetRewardFund
    | condenser_api.GetSavingsWithdrawFrom
    | condenser_api.GetSavingsWithdrawTo
    | condenser_api.GetTagsUsedByAuthor
    | condenser_api.GetTicker
    | condenser_api.GetTradeHistory
    | condenser_api.GetTransaction
    | condenser_api.GetTransactionHex
    | condenser_api.GetTrendingTags
    | condenser_api.GetVersion
    | condenser_api.GetVestingDelegations
    | condenser_api.GetVolume
    | condenser_api.GetWithdrawRoutes
    | condenser_api.GetWitnessByAccount
    | condenser_api.GetWitnessCount
    | condenser_api.GetWitnessSchedule
    | condenser_api.GetWitnesses
    | condenser_api.GetWitnessesByVote
    | condenser_api.IsKnownTransaction
    | condenser_api.ListProposalVotes
    | condenser_api.ListProposals
    | condenser_api.ListRcAccounts
    | condenser_api.ListRcDirectDelegations
    | condenser_api.ListVestingDelegations
    | condenser_api.LookupAccountNames
    | condenser_api.LookupAccounts
    | condenser_api.LookupWitnessAccounts
    | condenser_api.VerifyAccountAuthority
    | condenser_api.VerifyAuthority
    | database_api.FindAccountRecoveryRequests
    | database_api.FindAccounts
    | database_api.FindChangeRecoveryAccountRequests
    | database_api.FindCollateralizedConversionRequests
    | database_api.FindComments
    | database_api.FindDeclineVotingRightsRequests
    | database_api.FindEscrows
    | database_api.FindHbdConversionRequests
    | database_api.FindLimitOrders
    | database_api.FindOwnerHistories
    | database_api.FindProposals
    | database_api.FindRecurrentTransfers
    | database_api.FindSavingsWithdrawals
    | database_api.FindVestingDelegationExpirations
    | database_api.FindVestingDelegations
    | database_api.FindWithdrawVestingRoutes
    | database_api.FindWitnesses
    | database_api.GetActiveWitnesses
    | database_api.GetCommentPendingPayouts
    | database_api.GetConfig
    | database_api.GetCurrentPriceFeed
    | database_api.GetDynamicGlobalProperties
    | database_api.GetFeedHistory
    | database_api.GetHardforkProperties
    | database_api.GetOrderBook
    | database_api.GetPotentialSignatures
    | database_api.GetRequiredSignatures
    | database_api.GetRewardFunds
    | database_api.GetTransactionHex
    | database_api.GetVersion
    | database_api.GetWitnessSchedule
    | database_api.IsKnownTransaction
    | database_api.ListAccountRecoveryRequests
    | database_api.ListAccounts
    | database_api.ListChangeRecoveryAccountRequests
    | database_api.ListCollateralizedConversionRequests
    | database_api.ListComments
    | database_api.ListDeclineVotingRightsRequests
    | database_api.ListEscrows
    | database_api.ListHbdConversionRequests
    | database_api.ListLimitOrders
    | database_api.ListOwnerHistories
    | database_api.ListProposalVotes
    | database_api.ListProposals
    | database_api.ListSavingsWithdrawals
    | database_api.ListVestingDelegationExpirations
    | database_api.ListVestingDelegations
    | database_api.ListWithdrawVestingRoutes
    | database_api.ListWitnessVotes
    | database_api.ListWitnesses
    | database_api.VerifyAccountAuthority
    | database_api.VerifyAuthority
    | database_api.VerifySignatures
    | debug_node_api.DebugGenerateBlocks
    | debug_node_api.DebugGenerateBlocksUntil
    | debug_node_api.DebugGetHardforkPropertyObject
    | debug_node_api.DebugGetHeadBlock
    | debug_node_api.DebugGetJsonSchema
    | debug_node_api.DebugGetWitnessSchedule
    | debug_node_api.DebugHasHardfork
    | debug_node_api.DebugPopBlock
    | debug_node_api.DebugPushBlocks
    | debug_node_api.DebugSetHardfork
    | debug_node_api.DebugSetVestPrice
    | debug_node_api.DebugThrowException
    | jsonrpc.GetMethods
    | jsonrpc.GetSignature
    | market_history_api.GetMarketHistory
    | market_history_api.GetMarketHistoryBuckets
    | market_history_api.GetOrderBook
    | market_history_api.GetRecentTrades
    | market_history_api.GetTicker
    | market_history_api.GetTradeHistory
    | market_history_api.GetVolume
    | network_broadcast_api.BroadcastTransaction
    | network_node_api.AddNode
    | network_node_api.GetConnectedPeers
    | network_node_api.GetInfo
    | network_node_api.SetAllowedPeers
    | rc_api.FindRcAccounts
    | rc_api.GetResourceParams
    | rc_api.GetResourcePool
    | rc_api.ListRcAccounts
    | rc_api.ListRcDirectDelegations
    | reputation_api.GetAccountReputations
    | transaction_status_api.FindTransaction
    | wallet_bridge_api.BroadcastTransaction
    | wallet_bridge_api.BroadcastTransactionSynchronous
    | wallet_bridge_api.FindProposals
    | wallet_bridge_api.FindRcAccounts
    | wallet_bridge_api.FindRecurrentTransfers
    | wallet_bridge_api.GetAccount
    | wallet_bridge_api.GetAccountHistory
    | wallet_bridge_api.GetAccounts
    | wallet_bridge_api.GetActiveWitnesses
    | wallet_bridge_api.GetBlock
    | wallet_bridge_api.GetChainProperties
    | wallet_bridge_api.GetCollateralizedConversionRequests
    | wallet_bridge_api.GetConversionRequests
    | wallet_bridge_api.GetCurrentMedianHistoryPrice
    | wallet_bridge_api.GetDynamicGlobalProperties
    | wallet_bridge_api.GetFeedHistory
    | wallet_bridge_api.GetHardforkVersion
    | wallet_bridge_api.GetOpenOrders
    | wallet_bridge_api.GetOpsInBlock
    | wallet_bridge_api.GetOrderBook
    | wallet_bridge_api.GetOwnerHistory
    | wallet_bridge_api.GetRewardFund
    | wallet_bridge_api.GetTransaction
    | wallet_bridge_api.GetVersion
    | wallet_bridge_api.GetWithdrawRoutes
    | wallet_bridge_api.GetWitness
    | wallet_bridge_api.GetWitnessSchedule
    | wallet_bridge_api.IsKnownTransaction
    | wallet_bridge_api.ListAccounts
    | wallet_bridge_api.ListMyAccounts
    | wallet_bridge_api.ListProposalVotes
    | wallet_bridge_api.ListProposals
    | wallet_bridge_api.ListRcAccounts
    | wallet_bridge_api.ListRcDirectDelegations
    | wallet_bridge_api.ListWitnesses
)

ExpectResultT = TypeVar("ExpectResultT", bound=AllowedModelsAsResultT)


class JSONRPCResult(JSONRPCBase, Generic[ExpectResultT]):
    result: ExpectResultT


class AccountByKeyApiGetKeyReferencesJSONRPCBase(JSONRPCResult[account_by_key_api.GetKeyReferences]):
    result: account_by_key_api.GetKeyReferences


class AccountHistoryApiEnumVirtualOpsJSONRPCBase(JSONRPCResult[account_history_api.EnumVirtualOps]):
    result: account_history_api.EnumVirtualOps


class AccountHistoryApiGetAccountHistoryJSONRPCBase(JSONRPCResult[account_history_api.GetAccountHistory]):
    result: account_history_api.GetAccountHistory


class AccountHistoryApiGetOpsInBlockJSONRPCBase(JSONRPCResult[account_history_api.GetOpsInBlock]):
    result: account_history_api.GetOpsInBlock


class AccountHistoryApiGetTransactionJSONRPCBase(JSONRPCResult[account_history_api.GetTransaction]):
    result: account_history_api.GetTransaction


class BeekeeperApiCreateJSONRPCBase(JSONRPCResult[beekeeper_api.Create]):
    result: beekeeper_api.Create


class BeekeeperApiCreateSessionJSONRPCBase(JSONRPCResult[beekeeper_api.CreateSession]):
    result: beekeeper_api.CreateSession


class BeekeeperApiDecryptDataJSONRPCBase(JSONRPCResult[beekeeper_api.DecryptData]):
    result: beekeeper_api.DecryptData


class BeekeeperApiEmptyResponseJSONRPCBase(JSONRPCResult[beekeeper_api.EmptyResponse]):
    result: beekeeper_api.EmptyResponse


class BeekeeperApiEncryptDataJSONRPCBase(JSONRPCResult[beekeeper_api.EncryptData]):
    result: beekeeper_api.EncryptData


class BeekeeperApiGetInfoJSONRPCBase(JSONRPCResult[beekeeper_api.GetInfo]):
    result: beekeeper_api.GetInfo


class BeekeeperApiGetPublicKeysJSONRPCBase(JSONRPCResult[beekeeper_api.GetPublicKeys]):
    result: beekeeper_api.GetPublicKeys


class BeekeeperApiHasMatchingPrivateKeyJSONRPCBase(JSONRPCResult[beekeeper_api.HasMatchingPrivateKey]):
    result: beekeeper_api.HasMatchingPrivateKey


class BeekeeperApiImportKeyJSONRPCBase(JSONRPCResult[beekeeper_api.ImportKey]):
    result: beekeeper_api.ImportKey


class BeekeeperApiImportKeysJSONRPCBase(JSONRPCResult[beekeeper_api.ImportKeys]):
    result: beekeeper_api.ImportKeys


class BeekeeperApiListKeysJSONRPCBase(JSONRPCResult[beekeeper_api.ListKeys]):
    result: beekeeper_api.ListKeys


class BeekeeperApiListWalletsJSONRPCBase(JSONRPCResult[beekeeper_api.ListWallets]):
    result: beekeeper_api.ListWallets


class BeekeeperApiSignDigestJSONRPCBase(JSONRPCResult[beekeeper_api.SignDigest]):
    result: beekeeper_api.SignDigest


class BeekeeperApiSignTransactionJSONRPCBase(JSONRPCResult[beekeeper_api.SignTransaction]):
    result: beekeeper_api.SignTransaction


class BlockApiGetBlockJSONRPCBase(JSONRPCResult[block_api.GetBlock]):
    result: block_api.GetBlock


class BlockApiGetBlockHeaderJSONRPCBase(JSONRPCResult[block_api.GetBlockHeader]):
    result: block_api.GetBlockHeader


class BlockApiGetBlockRangeJSONRPCBase(JSONRPCResult[block_api.GetBlockRange]):
    result: block_api.GetBlockRange


class CondenserApiBroadcastTransactionJSONRPCBase(JSONRPCResult[condenser_api.BroadcastTransaction]):
    result: condenser_api.BroadcastTransaction


class CondenserApiBroadcastTransactionSynchronousJSONRPCBase(JSONRPCResult[condenser_api.BroadcastTransactionSynchronous]):
    result: condenser_api.BroadcastTransactionSynchronous


class CondenserApiFindProposalsJSONRPCBase(JSONRPCResult[condenser_api.FindProposals]):
    result: condenser_api.FindProposals


class CondenserApiFindRcAccountsJSONRPCBase(JSONRPCResult[condenser_api.FindRcAccounts]):
    result: condenser_api.FindRcAccounts


class CondenserApiFindRecurrentTransfersJSONRPCBase(JSONRPCResult[condenser_api.FindRecurrentTransfers]):
    result: condenser_api.FindRecurrentTransfers


class CondenserApiGetAccountCountJSONRPCBase(JSONRPCResult[condenser_api.GetAccountCount]):
    result: condenser_api.GetAccountCount


class CondenserApiGetAccountHistoryJSONRPCBase(JSONRPCResult[condenser_api.GetAccountHistory]):
    result: condenser_api.GetAccountHistory


class CondenserApiGetAccountReputationsJSONRPCBase(JSONRPCResult[condenser_api.GetAccountReputations]):
    result: condenser_api.GetAccountReputations


class CondenserApiGetAccountsJSONRPCBase(JSONRPCResult[condenser_api.GetAccounts]):
    result: condenser_api.GetAccounts


class CondenserApiGetActiveVotesJSONRPCBase(JSONRPCResult[condenser_api.GetActiveVotes]):
    result: condenser_api.GetActiveVotes


class CondenserApiGetActiveWitnessesJSONRPCBase(JSONRPCResult[condenser_api.GetActiveWitnesses]):
    result: condenser_api.GetActiveWitnesses


class CondenserApiGetBlockJSONRPCBase(JSONRPCResult[condenser_api.GetBlock]):
    result: condenser_api.GetBlock


class CondenserApiGetBlockHeaderJSONRPCBase(JSONRPCResult[condenser_api.GetBlockHeader]):
    result: condenser_api.GetBlockHeader


class CondenserApiGetBlogJSONRPCBase(JSONRPCResult[condenser_api.GetBlog]):
    result: condenser_api.GetBlog


class CondenserApiGetBlogEntriesJSONRPCBase(JSONRPCResult[condenser_api.GetBlogEntries]):
    result: condenser_api.GetBlogEntries


class CondenserApiGetChainPropertiesJSONRPCBase(JSONRPCResult[condenser_api.GetChainProperties]):
    result: condenser_api.GetChainProperties


class CondenserApiGetCollateralizedConversionRequestsJSONRPCBase(JSONRPCResult[condenser_api.GetCollateralizedConversionRequests]):
    result: condenser_api.GetCollateralizedConversionRequests


class CondenserApiGetCommentDiscussionsByPayoutJSONRPCBase(JSONRPCResult[condenser_api.GetCommentDiscussionsByPayout]):
    result: condenser_api.GetCommentDiscussionsByPayout


class CondenserApiGetConfigJSONRPCBase(JSONRPCResult[condenser_api.GetConfig]):
    result: condenser_api.GetConfig


class CondenserApiGetContentJSONRPCBase(JSONRPCResult[condenser_api.GetContent]):
    result: condenser_api.GetContent


class CondenserApiGetContentRepliesJSONRPCBase(JSONRPCResult[condenser_api.GetContentReplies]):
    result: condenser_api.GetContentReplies


class CondenserApiGetConversionRequestsJSONRPCBase(JSONRPCResult[condenser_api.GetConversionRequests]):
    result: condenser_api.GetConversionRequests


class CondenserApiGetCurrentMedianHistoryPriceJSONRPCBase(JSONRPCResult[condenser_api.GetCurrentMedianHistoryPrice]):
    result: condenser_api.GetCurrentMedianHistoryPrice


class CondenserApiGetDiscussionsByActiveJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByActive]):
    result: condenser_api.GetDiscussionsByActive


class CondenserApiGetDiscussionsByAuthorBeforeDateJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByAuthorBeforeDate]):
    result: condenser_api.GetDiscussionsByAuthorBeforeDate


class CondenserApiGetDiscussionsByBlogJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByBlog]):
    result: condenser_api.GetDiscussionsByBlog


class CondenserApiGetDiscussionsByCashoutJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByCashout]):
    result: condenser_api.GetDiscussionsByCashout


class CondenserApiGetDiscussionsByChildrenJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByChildren]):
    result: condenser_api.GetDiscussionsByChildren


class CondenserApiGetDiscussionsByCommentsJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByComments]):
    result: condenser_api.GetDiscussionsByComments


class CondenserApiGetDiscussionsByCreatedJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByCreated]):
    result: condenser_api.GetDiscussionsByCreated


class CondenserApiGetDiscussionsByFeedJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByFeed]):
    result: condenser_api.GetDiscussionsByFeed


class CondenserApiGetDiscussionsByHotJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByHot]):
    result: condenser_api.GetDiscussionsByHot


class CondenserApiGetDiscussionsByPromotedJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByPromoted]):
    result: condenser_api.GetDiscussionsByPromoted


class CondenserApiGetDiscussionsByTrendingJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByTrending]):
    result: condenser_api.GetDiscussionsByTrending


class CondenserApiGetDiscussionsByVotesJSONRPCBase(JSONRPCResult[condenser_api.GetDiscussionsByVotes]):
    result: condenser_api.GetDiscussionsByVotes


class CondenserApiGetDynamicGlobalPropertiesJSONRPCBase(JSONRPCResult[condenser_api.GetDynamicGlobalProperties]):
    result: condenser_api.GetDynamicGlobalProperties


class CondenserApiGetEscrowJSONRPCBase(JSONRPCResult[condenser_api.GetEscrow]):
    result: condenser_api.GetEscrow


class CondenserApiGetExpiringVestingDelegationJSONRPCBase(JSONRPCResult[condenser_api.GetExpiringVestingDelegation]):
    result: condenser_api.GetExpiringVestingDelegation


class CondenserApiGetExpiringVestingDelegationsJSONRPCBase(JSONRPCResult[condenser_api.GetExpiringVestingDelegations]):
    result: condenser_api.GetExpiringVestingDelegations


class CondenserApiGetFeedJSONRPCBase(JSONRPCResult[condenser_api.GetFeed]):
    result: condenser_api.GetFeed


class CondenserApiGetFeedEntriesJSONRPCBase(JSONRPCResult[condenser_api.GetFeedEntries]):
    result: condenser_api.GetFeedEntries


class CondenserApiGetFeedHistoryJSONRPCBase(JSONRPCResult[condenser_api.GetFeedHistory]):
    result: condenser_api.GetFeedHistory


class CondenserApiGetFollowCountJSONRPCBase(JSONRPCResult[condenser_api.GetFollowCount]):
    result: condenser_api.GetFollowCount


class CondenserApiGetFollowersJSONRPCBase(JSONRPCResult[condenser_api.GetFollowers]):
    result: condenser_api.GetFollowers


class CondenserApiGetFollowingJSONRPCBase(JSONRPCResult[condenser_api.GetFollowing]):
    result: condenser_api.GetFollowing


class CondenserApiGetHardforkVersionJSONRPCBase(JSONRPCResult[condenser_api.GetHardforkVersion]):
    result: condenser_api.GetHardforkVersion


class CondenserApiGetKeyReferencesJSONRPCBase(JSONRPCResult[condenser_api.GetKeyReferences]):
    result: condenser_api.GetKeyReferences


class CondenserApiGetMarketHistoryJSONRPCBase(JSONRPCResult[condenser_api.GetMarketHistory]):
    result: condenser_api.GetMarketHistory


class CondenserApiGetMarketHistoryBucketsJSONRPCBase(JSONRPCResult[condenser_api.GetMarketHistoryBuckets]):
    result: condenser_api.GetMarketHistoryBuckets


class CondenserApiGetNextScheduledHardforkJSONRPCBase(JSONRPCResult[condenser_api.GetNextScheduledHardfork]):
    result: condenser_api.GetNextScheduledHardfork


class CondenserApiGetOpenOrdersJSONRPCBase(JSONRPCResult[condenser_api.GetOpenOrders]):
    result: condenser_api.GetOpenOrders


class CondenserApiGetOpsInBlockJSONRPCBase(JSONRPCResult[condenser_api.GetOpsInBlock]):
    result: condenser_api.GetOpsInBlock


class CondenserApiGetOrderBookJSONRPCBase(JSONRPCResult[condenser_api.GetOrderBook]):
    result: condenser_api.GetOrderBook


class CondenserApiGetOwnerHistoryJSONRPCBase(JSONRPCResult[condenser_api.GetOwnerHistory]):
    result: condenser_api.GetOwnerHistory


class CondenserApiGetPostDiscussionsByPayoutJSONRPCBase(JSONRPCResult[condenser_api.GetPostDiscussionsByPayout]):
    result: condenser_api.GetPostDiscussionsByPayout


class CondenserApiGetPotentialSignaturesJSONRPCBase(JSONRPCResult[condenser_api.GetPotentialSignatures]):
    result: condenser_api.GetPotentialSignatures


class CondenserApiGetRebloggedByJSONRPCBase(JSONRPCResult[condenser_api.GetRebloggedBy]):
    result: condenser_api.GetRebloggedBy


class CondenserApiGetRecentTradesJSONRPCBase(JSONRPCResult[condenser_api.GetRecentTrades]):
    result: condenser_api.GetRecentTrades


class CondenserApiGetRecoveryRequestJSONRPCBase(JSONRPCResult[condenser_api.GetRecoveryRequest]):
    result: condenser_api.GetRecoveryRequest


class CondenserApiGetRepliesByLastUpdateJSONRPCBase(JSONRPCResult[condenser_api.GetRepliesByLastUpdate]):
    result: condenser_api.GetRepliesByLastUpdate


class CondenserApiGetRequiredSignaturesJSONRPCBase(JSONRPCResult[condenser_api.GetRequiredSignatures]):
    result: condenser_api.GetRequiredSignatures


class CondenserApiGetRewardFundJSONRPCBase(JSONRPCResult[condenser_api.GetRewardFund]):
    result: condenser_api.GetRewardFund


class CondenserApiGetSavingsWithdrawFromJSONRPCBase(JSONRPCResult[condenser_api.GetSavingsWithdrawFrom]):
    result: condenser_api.GetSavingsWithdrawFrom


class CondenserApiGetSavingsWithdrawToJSONRPCBase(JSONRPCResult[condenser_api.GetSavingsWithdrawTo]):
    result: condenser_api.GetSavingsWithdrawTo


class CondenserApiGetTagsUsedByAuthorJSONRPCBase(JSONRPCResult[condenser_api.GetTagsUsedByAuthor]):
    result: condenser_api.GetTagsUsedByAuthor


class CondenserApiGetTickerJSONRPCBase(JSONRPCResult[condenser_api.GetTicker]):
    result: condenser_api.GetTicker


class CondenserApiGetTradeHistoryJSONRPCBase(JSONRPCResult[condenser_api.GetTradeHistory]):
    result: condenser_api.GetTradeHistory


class CondenserApiGetTransactionJSONRPCBase(JSONRPCResult[condenser_api.GetTransaction]):
    result: condenser_api.GetTransaction


class CondenserApiGetTransactionHexJSONRPCBase(JSONRPCResult[condenser_api.GetTransactionHex]):
    result: condenser_api.GetTransactionHex


class CondenserApiGetTrendingTagsJSONRPCBase(JSONRPCResult[condenser_api.GetTrendingTags]):
    result: condenser_api.GetTrendingTags


class CondenserApiGetVersionJSONRPCBase(JSONRPCResult[condenser_api.GetVersion]):
    result: condenser_api.GetVersion


class CondenserApiGetVestingDelegationsJSONRPCBase(JSONRPCResult[condenser_api.GetVestingDelegations]):
    result: condenser_api.GetVestingDelegations


class CondenserApiGetVolumeJSONRPCBase(JSONRPCResult[condenser_api.GetVolume]):
    result: condenser_api.GetVolume


class CondenserApiGetWithdrawRoutesJSONRPCBase(JSONRPCResult[condenser_api.GetWithdrawRoutes]):
    result: condenser_api.GetWithdrawRoutes


class CondenserApiGetWitnessByAccountJSONRPCBase(JSONRPCResult[condenser_api.GetWitnessByAccount]):
    result: condenser_api.GetWitnessByAccount


class CondenserApiGetWitnessCountJSONRPCBase(JSONRPCResult[condenser_api.GetWitnessCount]):
    result: condenser_api.GetWitnessCount


class CondenserApiGetWitnessScheduleJSONRPCBase(JSONRPCResult[condenser_api.GetWitnessSchedule]):
    result: condenser_api.GetWitnessSchedule


class CondenserApiGetWitnessesJSONRPCBase(JSONRPCResult[condenser_api.GetWitnesses]):
    result: condenser_api.GetWitnesses


class CondenserApiGetWitnessesByVoteJSONRPCBase(JSONRPCResult[condenser_api.GetWitnessesByVote]):
    result: condenser_api.GetWitnessesByVote


class CondenserApiIsKnownTransactionJSONRPCBase(JSONRPCResult[condenser_api.IsKnownTransaction]):
    result: condenser_api.IsKnownTransaction


class CondenserApiListProposalVotesJSONRPCBase(JSONRPCResult[condenser_api.ListProposalVotes]):
    result: condenser_api.ListProposalVotes


class CondenserApiListProposalsJSONRPCBase(JSONRPCResult[condenser_api.ListProposals]):
    result: condenser_api.ListProposals


class CondenserApiListRcAccountsJSONRPCBase(JSONRPCResult[condenser_api.ListRcAccounts]):
    result: condenser_api.ListRcAccounts


class CondenserApiListRcDirectDelegationsJSONRPCBase(JSONRPCResult[condenser_api.ListRcDirectDelegations]):
    result: condenser_api.ListRcDirectDelegations


class CondenserApiListVestingDelegationsJSONRPCBase(JSONRPCResult[condenser_api.ListVestingDelegations]):
    result: condenser_api.ListVestingDelegations


class CondenserApiLookupAccountNamesJSONRPCBase(JSONRPCResult[condenser_api.LookupAccountNames]):
    result: condenser_api.LookupAccountNames


class CondenserApiLookupAccountsJSONRPCBase(JSONRPCResult[condenser_api.LookupAccounts]):
    result: condenser_api.LookupAccounts


class CondenserApiLookupWitnessAccountsJSONRPCBase(JSONRPCResult[condenser_api.LookupWitnessAccounts]):
    result: condenser_api.LookupWitnessAccounts


class CondenserApiVerifyAccountAuthorityJSONRPCBase(JSONRPCResult[condenser_api.VerifyAccountAuthority]):
    result: condenser_api.VerifyAccountAuthority


class CondenserApiVerifyAuthorityJSONRPCBase(JSONRPCResult[condenser_api.VerifyAuthority]):
    result: condenser_api.VerifyAuthority


class DatabaseApiFindAccountRecoveryRequestsJSONRPCBase(JSONRPCResult[database_api.FindAccountRecoveryRequests]):
    result: database_api.FindAccountRecoveryRequests


class DatabaseApiFindAccountsJSONRPCBase(JSONRPCResult[database_api.FindAccounts]):
    result: database_api.FindAccounts


class DatabaseApiFindChangeRecoveryAccountRequestsJSONRPCBase(JSONRPCResult[database_api.FindChangeRecoveryAccountRequests]):
    result: database_api.FindChangeRecoveryAccountRequests


class DatabaseApiFindCollateralizedConversionRequestsJSONRPCBase(JSONRPCResult[database_api.FindCollateralizedConversionRequests]):
    result: database_api.FindCollateralizedConversionRequests


class DatabaseApiFindCommentsJSONRPCBase(JSONRPCResult[database_api.FindComments]):
    result: database_api.FindComments


class DatabaseApiFindDeclineVotingRightsRequestsJSONRPCBase(JSONRPCResult[database_api.FindDeclineVotingRightsRequests]):
    result: database_api.FindDeclineVotingRightsRequests


class DatabaseApiFindEscrowsJSONRPCBase(JSONRPCResult[database_api.FindEscrows]):
    result: database_api.FindEscrows


class DatabaseApiFindHbdConversionRequestsJSONRPCBase(JSONRPCResult[database_api.FindHbdConversionRequests]):
    result: database_api.FindHbdConversionRequests


class DatabaseApiFindLimitOrdersJSONRPCBase(JSONRPCResult[database_api.FindLimitOrders]):
    result: database_api.FindLimitOrders


class DatabaseApiFindOwnerHistoriesJSONRPCBase(JSONRPCResult[database_api.FindOwnerHistories]):
    result: database_api.FindOwnerHistories


class DatabaseApiFindProposalsJSONRPCBase(JSONRPCResult[database_api.FindProposals]):
    result: database_api.FindProposals


class DatabaseApiFindRecurrentTransfersJSONRPCBase(JSONRPCResult[database_api.FindRecurrentTransfers]):
    result: database_api.FindRecurrentTransfers


class DatabaseApiFindSavingsWithdrawalsJSONRPCBase(JSONRPCResult[database_api.FindSavingsWithdrawals]):
    result: database_api.FindSavingsWithdrawals


class DatabaseApiFindVestingDelegationExpirationsJSONRPCBase(JSONRPCResult[database_api.FindVestingDelegationExpirations]):
    result: database_api.FindVestingDelegationExpirations


class DatabaseApiFindVestingDelegationsJSONRPCBase(JSONRPCResult[database_api.FindVestingDelegations]):
    result: database_api.FindVestingDelegations


class DatabaseApiFindWithdrawVestingRoutesJSONRPCBase(JSONRPCResult[database_api.FindWithdrawVestingRoutes]):
    result: database_api.FindWithdrawVestingRoutes


class DatabaseApiFindWitnessesJSONRPCBase(JSONRPCResult[database_api.FindWitnesses]):
    result: database_api.FindWitnesses


class DatabaseApiGetActiveWitnessesJSONRPCBase(JSONRPCResult[database_api.GetActiveWitnesses]):
    result: database_api.GetActiveWitnesses


class DatabaseApiGetCommentPendingPayoutsJSONRPCBase(JSONRPCResult[database_api.GetCommentPendingPayouts]):
    result: database_api.GetCommentPendingPayouts


class DatabaseApiGetConfigJSONRPCBase(JSONRPCResult[database_api.GetConfig]):
    result: database_api.GetConfig


class DatabaseApiGetCurrentPriceFeedJSONRPCBase(JSONRPCResult[database_api.GetCurrentPriceFeed]):
    result: database_api.GetCurrentPriceFeed


class DatabaseApiGetDynamicGlobalPropertiesJSONRPCBase(JSONRPCResult[database_api.GetDynamicGlobalProperties]):
    result: database_api.GetDynamicGlobalProperties


class DatabaseApiGetFeedHistoryJSONRPCBase(JSONRPCResult[database_api.GetFeedHistory]):
    result: database_api.GetFeedHistory


class DatabaseApiGetHardforkPropertiesJSONRPCBase(JSONRPCResult[database_api.GetHardforkProperties]):
    result: database_api.GetHardforkProperties


class DatabaseApiGetOrderBookJSONRPCBase(JSONRPCResult[database_api.GetOrderBook]):
    result: database_api.GetOrderBook


class DatabaseApiGetPotentialSignaturesJSONRPCBase(JSONRPCResult[database_api.GetPotentialSignatures]):
    result: database_api.GetPotentialSignatures


class DatabaseApiGetRequiredSignaturesJSONRPCBase(JSONRPCResult[database_api.GetRequiredSignatures]):
    result: database_api.GetRequiredSignatures


class DatabaseApiGetRewardFundsJSONRPCBase(JSONRPCResult[database_api.GetRewardFunds]):
    result: database_api.GetRewardFunds


class DatabaseApiGetTransactionHexJSONRPCBase(JSONRPCResult[database_api.GetTransactionHex]):
    result: database_api.GetTransactionHex


class DatabaseApiGetVersionJSONRPCBase(JSONRPCResult[database_api.GetVersion]):
    result: database_api.GetVersion


class DatabaseApiGetWitnessScheduleJSONRPCBase(JSONRPCResult[database_api.GetWitnessSchedule]):
    result: database_api.GetWitnessSchedule


class DatabaseApiIsKnownTransactionJSONRPCBase(JSONRPCResult[database_api.IsKnownTransaction]):
    result: database_api.IsKnownTransaction


class DatabaseApiListAccountRecoveryRequestsJSONRPCBase(JSONRPCResult[database_api.ListAccountRecoveryRequests]):
    result: database_api.ListAccountRecoveryRequests


class DatabaseApiListAccountsJSONRPCBase(JSONRPCResult[database_api.ListAccounts]):
    result: database_api.ListAccounts


class DatabaseApiListChangeRecoveryAccountRequestsJSONRPCBase(JSONRPCResult[database_api.ListChangeRecoveryAccountRequests]):
    result: database_api.ListChangeRecoveryAccountRequests


class DatabaseApiListCollateralizedConversionRequestsJSONRPCBase(JSONRPCResult[database_api.ListCollateralizedConversionRequests]):
    result: database_api.ListCollateralizedConversionRequests


class DatabaseApiListCommentsJSONRPCBase(JSONRPCResult[database_api.ListComments]):
    result: database_api.ListComments


class DatabaseApiListDeclineVotingRightsRequestsJSONRPCBase(JSONRPCResult[database_api.ListDeclineVotingRightsRequests]):
    result: database_api.ListDeclineVotingRightsRequests


class DatabaseApiListEscrowsJSONRPCBase(JSONRPCResult[database_api.ListEscrows]):
    result: database_api.ListEscrows


class DatabaseApiListHbdConversionRequestsJSONRPCBase(JSONRPCResult[database_api.ListHbdConversionRequests]):
    result: database_api.ListHbdConversionRequests


class DatabaseApiListLimitOrdersJSONRPCBase(JSONRPCResult[database_api.ListLimitOrders]):
    result: database_api.ListLimitOrders


class DatabaseApiListOwnerHistoriesJSONRPCBase(JSONRPCResult[database_api.ListOwnerHistories]):
    result: database_api.ListOwnerHistories


class DatabaseApiListProposalVotesJSONRPCBase(JSONRPCResult[database_api.ListProposalVotes]):
    result: database_api.ListProposalVotes


class DatabaseApiListProposalsJSONRPCBase(JSONRPCResult[database_api.ListProposals]):
    result: database_api.ListProposals


class DatabaseApiListSavingsWithdrawalsJSONRPCBase(JSONRPCResult[database_api.ListSavingsWithdrawals]):
    result: database_api.ListSavingsWithdrawals


class DatabaseApiListVestingDelegationExpirationsJSONRPCBase(JSONRPCResult[database_api.ListVestingDelegationExpirations]):
    result: database_api.ListVestingDelegationExpirations


class DatabaseApiListVestingDelegationsJSONRPCBase(JSONRPCResult[database_api.ListVestingDelegations]):
    result: database_api.ListVestingDelegations


class DatabaseApiListWithdrawVestingRoutesJSONRPCBase(JSONRPCResult[database_api.ListWithdrawVestingRoutes]):
    result: database_api.ListWithdrawVestingRoutes


class DatabaseApiListWitnessVotesJSONRPCBase(JSONRPCResult[database_api.ListWitnessVotes]):
    result: database_api.ListWitnessVotes


class DatabaseApiListWitnessesJSONRPCBase(JSONRPCResult[database_api.ListWitnesses]):
    result: database_api.ListWitnesses


class DatabaseApiVerifyAccountAuthorityJSONRPCBase(JSONRPCResult[database_api.VerifyAccountAuthority]):
    result: database_api.VerifyAccountAuthority


class DatabaseApiVerifyAuthorityJSONRPCBase(JSONRPCResult[database_api.VerifyAuthority]):
    result: database_api.VerifyAuthority


class DatabaseApiVerifySignaturesJSONRPCBase(JSONRPCResult[database_api.VerifySignatures]):
    result: database_api.VerifySignatures


class DebugNodeApiDebugGenerateBlocksJSONRPCBase(JSONRPCResult[debug_node_api.DebugGenerateBlocks]):
    result: debug_node_api.DebugGenerateBlocks


class DebugNodeApiDebugGenerateBlocksUntilJSONRPCBase(JSONRPCResult[debug_node_api.DebugGenerateBlocksUntil]):
    result: debug_node_api.DebugGenerateBlocksUntil


class DebugNodeApiDebugGetHardforkPropertyObjectJSONRPCBase(JSONRPCResult[debug_node_api.DebugGetHardforkPropertyObject]):
    result: debug_node_api.DebugGetHardforkPropertyObject


class DebugNodeApiDebugGetHeadBlockJSONRPCBase(JSONRPCResult[debug_node_api.DebugGetHeadBlock]):
    result: debug_node_api.DebugGetHeadBlock


class DebugNodeApiDebugGetJsonSchemaJSONRPCBase(JSONRPCResult[debug_node_api.DebugGetJsonSchema]):
    result: debug_node_api.DebugGetJsonSchema


class DebugNodeApiDebugGetWitnessScheduleJSONRPCBase(JSONRPCResult[debug_node_api.DebugGetWitnessSchedule]):
    result: debug_node_api.DebugGetWitnessSchedule


class DebugNodeApiDebugHasHardforkJSONRPCBase(JSONRPCResult[debug_node_api.DebugHasHardfork]):
    result: debug_node_api.DebugHasHardfork


class DebugNodeApiDebugPopBlockJSONRPCBase(JSONRPCResult[debug_node_api.DebugPopBlock]):
    result: debug_node_api.DebugPopBlock


class DebugNodeApiDebugPushBlocksJSONRPCBase(JSONRPCResult[debug_node_api.DebugPushBlocks]):
    result: debug_node_api.DebugPushBlocks


class DebugNodeApiDebugSetHardforkJSONRPCBase(JSONRPCResult[debug_node_api.DebugSetHardfork]):
    result: debug_node_api.DebugSetHardfork


class DebugNodeApiDebugSetVestPriceJSONRPCBase(JSONRPCResult[debug_node_api.DebugSetVestPrice]):
    result: debug_node_api.DebugSetVestPrice


class DebugNodeApiDebugThrowExceptionJSONRPCBase(JSONRPCResult[debug_node_api.DebugThrowException]):
    result: debug_node_api.DebugThrowException


class JsonrpcGetMethodsJSONRPCBase(JSONRPCResult[jsonrpc.GetMethods]):
    result: jsonrpc.GetMethods


class JsonrpcGetSignatureJSONRPCBase(JSONRPCResult[jsonrpc.GetSignature]):
    result: jsonrpc.GetSignature


class MarketHistoryApiGetMarketHistoryJSONRPCBase(JSONRPCResult[market_history_api.GetMarketHistory]):
    result: market_history_api.GetMarketHistory


class MarketHistoryApiGetMarketHistoryBucketsJSONRPCBase(JSONRPCResult[market_history_api.GetMarketHistoryBuckets]):
    result: market_history_api.GetMarketHistoryBuckets


class MarketHistoryApiGetOrderBookJSONRPCBase(JSONRPCResult[market_history_api.GetOrderBook]):
    result: market_history_api.GetOrderBook


class MarketHistoryApiGetRecentTradesJSONRPCBase(JSONRPCResult[market_history_api.GetRecentTrades]):
    result: market_history_api.GetRecentTrades


class MarketHistoryApiGetTickerJSONRPCBase(JSONRPCResult[market_history_api.GetTicker]):
    result: market_history_api.GetTicker


class MarketHistoryApiGetTradeHistoryJSONRPCBase(JSONRPCResult[market_history_api.GetTradeHistory]):
    result: market_history_api.GetTradeHistory


class MarketHistoryApiGetVolumeJSONRPCBase(JSONRPCResult[market_history_api.GetVolume]):
    result: market_history_api.GetVolume


class NetworkBroadcastApiBroadcastTransactionJSONRPCBase(JSONRPCResult[network_broadcast_api.BroadcastTransaction]):
    result: network_broadcast_api.BroadcastTransaction


class NetworkNodeApiAddNodeJSONRPCBase(JSONRPCResult[network_node_api.AddNode]):
    result: network_node_api.AddNode


class NetworkNodeApiGetConnectedPeersJSONRPCBase(JSONRPCResult[network_node_api.GetConnectedPeers]):
    result: network_node_api.GetConnectedPeers


class NetworkNodeApiGetInfoJSONRPCBase(JSONRPCResult[network_node_api.GetInfo]):
    result: network_node_api.GetInfo


class NetworkNodeApiSetAllowedPeersJSONRPCBase(JSONRPCResult[network_node_api.SetAllowedPeers]):
    result: network_node_api.SetAllowedPeers


class RcApiFindRcAccountsJSONRPCBase(JSONRPCResult[rc_api.FindRcAccounts]):
    result: rc_api.FindRcAccounts


class RcApiGetResourceParamsJSONRPCBase(JSONRPCResult[rc_api.GetResourceParams]):
    result: rc_api.GetResourceParams


class RcApiGetResourcePoolJSONRPCBase(JSONRPCResult[rc_api.GetResourcePool]):
    result: rc_api.GetResourcePool


class RcApiListRcAccountsJSONRPCBase(JSONRPCResult[rc_api.ListRcAccounts]):
    result: rc_api.ListRcAccounts


class RcApiListRcDirectDelegationsJSONRPCBase(JSONRPCResult[rc_api.ListRcDirectDelegations]):
    result: rc_api.ListRcDirectDelegations


class ReputationApiGetAccountReputationsJSONRPCBase(JSONRPCResult[reputation_api.GetAccountReputations]):
    result: reputation_api.GetAccountReputations


class TransactionStatusApiFindTransactionJSONRPCBase(JSONRPCResult[transaction_status_api.FindTransaction]):
    result: transaction_status_api.FindTransaction


class WalletBridgeApiBroadcastTransactionJSONRPCBase(JSONRPCResult[wallet_bridge_api.BroadcastTransaction]):
    result: wallet_bridge_api.BroadcastTransaction


class WalletBridgeApiBroadcastTransactionSynchronousJSONRPCBase(JSONRPCResult[wallet_bridge_api.BroadcastTransactionSynchronous]):
    result: wallet_bridge_api.BroadcastTransactionSynchronous


class WalletBridgeApiFindProposalsJSONRPCBase(JSONRPCResult[wallet_bridge_api.FindProposals]):
    result: wallet_bridge_api.FindProposals


class WalletBridgeApiFindRcAccountsJSONRPCBase(JSONRPCResult[wallet_bridge_api.FindRcAccounts]):
    result: wallet_bridge_api.FindRcAccounts


class WalletBridgeApiFindRecurrentTransfersJSONRPCBase(JSONRPCResult[wallet_bridge_api.FindRecurrentTransfers]):
    result: wallet_bridge_api.FindRecurrentTransfers


class WalletBridgeApiGetAccountJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetAccount]):
    result: wallet_bridge_api.GetAccount


class WalletBridgeApiGetAccountHistoryJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetAccountHistory]):
    result: wallet_bridge_api.GetAccountHistory


class WalletBridgeApiGetAccountsJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetAccounts]):
    result: wallet_bridge_api.GetAccounts


class WalletBridgeApiGetActiveWitnessesJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetActiveWitnesses]):
    result: wallet_bridge_api.GetActiveWitnesses


class WalletBridgeApiGetBlockJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetBlock]):
    result: wallet_bridge_api.GetBlock


class WalletBridgeApiGetChainPropertiesJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetChainProperties]):
    result: wallet_bridge_api.GetChainProperties


class WalletBridgeApiGetCollateralizedConversionRequestsJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetCollateralizedConversionRequests]):
    result: wallet_bridge_api.GetCollateralizedConversionRequests


class WalletBridgeApiGetConversionRequestsJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetConversionRequests]):
    result: wallet_bridge_api.GetConversionRequests


class WalletBridgeApiGetCurrentMedianHistoryPriceJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetCurrentMedianHistoryPrice]):
    result: wallet_bridge_api.GetCurrentMedianHistoryPrice


class WalletBridgeApiGetDynamicGlobalPropertiesJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetDynamicGlobalProperties]):
    result: wallet_bridge_api.GetDynamicGlobalProperties


class WalletBridgeApiGetFeedHistoryJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetFeedHistory]):
    result: wallet_bridge_api.GetFeedHistory


class WalletBridgeApiGetHardforkVersionJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetHardforkVersion]):
    result: wallet_bridge_api.GetHardforkVersion


class WalletBridgeApiGetOpenOrdersJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetOpenOrders]):
    result: wallet_bridge_api.GetOpenOrders


class WalletBridgeApiGetOpsInBlockJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetOpsInBlock]):
    result: wallet_bridge_api.GetOpsInBlock


class WalletBridgeApiGetOrderBookJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetOrderBook]):
    result: wallet_bridge_api.GetOrderBook


class WalletBridgeApiGetOwnerHistoryJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetOwnerHistory]):
    result: wallet_bridge_api.GetOwnerHistory


class WalletBridgeApiGetRewardFundJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetRewardFund]):
    result: wallet_bridge_api.GetRewardFund


class WalletBridgeApiGetTransactionJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetTransaction]):
    result: wallet_bridge_api.GetTransaction


class WalletBridgeApiGetVersionJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetVersion]):
    result: wallet_bridge_api.GetVersion


class WalletBridgeApiGetWithdrawRoutesJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetWithdrawRoutes]):
    result: wallet_bridge_api.GetWithdrawRoutes


class WalletBridgeApiGetWitnessJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetWitness]):
    result: wallet_bridge_api.GetWitness


class WalletBridgeApiGetWitnessScheduleJSONRPCBase(JSONRPCResult[wallet_bridge_api.GetWitnessSchedule]):
    result: wallet_bridge_api.GetWitnessSchedule


class WalletBridgeApiIsKnownTransactionJSONRPCBase(JSONRPCResult[wallet_bridge_api.IsKnownTransaction]):
    result: wallet_bridge_api.IsKnownTransaction


class WalletBridgeApiListAccountsJSONRPCBase(JSONRPCResult[wallet_bridge_api.ListAccounts]):
    result: wallet_bridge_api.ListAccounts


class WalletBridgeApiListMyAccountsJSONRPCBase(JSONRPCResult[wallet_bridge_api.ListMyAccounts]):
    result: wallet_bridge_api.ListMyAccounts


class WalletBridgeApiListProposalVotesJSONRPCBase(JSONRPCResult[wallet_bridge_api.ListProposalVotes]):
    result: wallet_bridge_api.ListProposalVotes


class WalletBridgeApiListProposalsJSONRPCBase(JSONRPCResult[wallet_bridge_api.ListProposals]):
    result: wallet_bridge_api.ListProposals


class WalletBridgeApiListRcAccountsJSONRPCBase(JSONRPCResult[wallet_bridge_api.ListRcAccounts]):
    result: wallet_bridge_api.ListRcAccounts


class WalletBridgeApiListRcDirectDelegationsJSONRPCBase(JSONRPCResult[wallet_bridge_api.ListRcDirectDelegations]):
    result: wallet_bridge_api.ListRcDirectDelegations


class WalletBridgeApiListWitnessesJSONRPCBase(JSONRPCResult[wallet_bridge_api.ListWitnesses]):
    result: wallet_bridge_api.ListWitnesses


def get_jsonrpc_response_types_name(expected_model: type[ExpectResultT], endpoint: str) -> type:
    def convert_to_pascal_case(name: str) -> str:
        return "".join(word.title() for word in name.split("_"))

    api_name, class_name = endpoint.split(sep=".")
    if "EmptyResponse" in str(expected_model):
        jsonrpc_model_name = "BeekeeperApiEmptyResponseJSONRPCBase"
    else:
        jsonrpc_model_name = f"{convert_to_pascal_case(api_name)}{convert_to_pascal_case(class_name)}JSONRPCBase"

    jsonrpc_model = globals().get(jsonrpc_model_name)
    assert jsonrpc_model is not None, f"Missing model for: {endpoint}"
    return cast(type, jsonrpc_model)
