from __future__ import annotations

from schemas.__private.operations.virtual import (
    AccountCreatedOperation,
    AnyLegacyVirtualOperation,
    AnyVirtualOperation,
    AuthorRewardOperation,
    ChangedRecoveryAccountOperation,
    ClearNullAccountBalanceOperation,
    CollateralizedConvertImmediateConversionOperation,
    CommentBenefactorRewardOperation,
    CommentPayoutUpdateOperation,
    CommentRewardOperation,
    ConsolidateTreasuryBalanceOperation,
    CurationRewardOperation,
    DeclinedVotingRightsOperation,
    DelayedVotingOperation,
    DhfConversionOperation,
    DhfFundingOperation,
    EffectiveCommentVoteOperation,
    EscrowApprovedOperation,
    EscrowRejectedOperation,
    ExpiredAccountNotificationOperation,
    FailedRecurrentTransferOperation,
    FillCollateralizedConvertRequestOperation,
    FillConvertRequestOperation,
    FillOrderOperation,
    FillRecurrentTransferOperation,
    FillTransferFromSavingsOperation,
    FillVestingWithdrawOperation,
    HardforkHiveOperation,
    HardforkHiveRestoreOperation,
    HardforkOperation,
    IneffectiveDeleteCommentOperation,
    InterestOperation,
    LimitOrderCancelledOperation,
    LiquidityRewardOperation,
    PowRewardOperation,
    ProducerMissedOperation,
    ProducerRewardOperation,
    ProposalFeeOperation,
    ProposalPayOperation,
    ProxyClearedOperation,
    ReturnVestingDelegationOperation,
    ShutDownWitnessOperation,
    SystemWarningOperation,
    TransferToVestingCompletedOperation,
    VestingSharesSplitOperation,
)
from schemas.__private.operations.virtual.representation_types import (
    Hf26VirtualOperationRepresentationType,
    LegacyVirtualOperationRepresentationType,
)
from schemas.__private.virtual_operation import VirtualOperation

__all__ = [
    "VirtualOperation",
    # REPRESENTATIONS
    "Hf26VirtualOperationRepresentationType",
    "LegacyVirtualOperationRepresentationType",
    # ANY OPERATION
    "AnyVirtualOperation",
    "AnyLegacyVirtualOperation",
    # OPERATIONS
    "AccountCreatedOperation",
    "AuthorRewardOperation",
    "ChangedRecoveryAccountOperation",
    "ClearNullAccountBalanceOperation",
    "CollateralizedConvertImmediateConversionOperation",
    "CommentBenefactorRewardOperation",
    "CommentPayoutUpdateOperation",
    "CommentRewardOperation",
    "ConsolidateTreasuryBalanceOperation",
    "CurationRewardOperation",
    "DeclinedVotingRightsOperation",
    "DelayedVotingOperation",
    "DhfConversionOperation",
    "DhfFundingOperation",
    "EffectiveCommentVoteOperation",
    "EscrowApprovedOperation",
    "EscrowRejectedOperation",
    "ExpiredAccountNotificationOperation",
    "FailedRecurrentTransferOperation",
    "FillCollateralizedConvertRequestOperation",
    "FillConvertRequestOperation",
    "FillOrderOperation",
    "FillRecurrentTransferOperation",
    "FillTransferFromSavingsOperation",
    "FillVestingWithdrawOperation",
    "HardforkHiveOperation",
    "HardforkHiveRestoreOperation",
    "HardforkOperation",
    "IneffectiveDeleteCommentOperation",
    "InterestOperation",
    "LimitOrderCancelledOperation",
    "LiquidityRewardOperation",
    "PowRewardOperation",
    "ProducerMissedOperation",
    "ProducerRewardOperation",
    "ProposalFeeOperation",
    "ProposalPayOperation",
    "ProxyClearedOperation",
    "ReturnVestingDelegationOperation",
    "ShutDownWitnessOperation",
    "SystemWarningOperation",
    "TransferToVestingCompletedOperation",
    "VestingSharesSplitOperation",
]
