# fmt: off

# WARNING: This code was automatically generated by a script.
# DO NOT EDIT this file manually, as any changes may be overwritten.
# If modifications are needed, please update the generating script instead.

from __future__ import annotations

from typing import Any, Generic, Literal, TypeVar, overload

from schemas._preconfigured_base_model import DictStrAny, PreconfiguredBaseModel
from schemas.operation import OperationBase, Representible
from schemas.operations.account_create_operation import AccountCreateOperation
from schemas.operations.account_create_with_delegation_operation import AccountCreateWithDelegationOperation
from schemas.operations.account_update2_operation import AccountUpdate2Operation
from schemas.operations.account_update_operation import AccountUpdateOperation
from schemas.operations.account_witness_proxy_operation import AccountWitnessProxyOperation
from schemas.operations.account_witness_vote_operation import AccountWitnessVoteOperation
from schemas.operations.cancel_transfer_from_savings_operation import CancelTransferFromSavingsOperation
from schemas.operations.change_recovery_account_operation import ChangeRecoveryAccountOperation
from schemas.operations.claim_account_operation import ClaimAccountOperation
from schemas.operations.claim_reward_balance_operation import ClaimRewardBalanceOperation
from schemas.operations.collateralized_convert_operation import CollateralizedConvertOperation
from schemas.operations.comment_operation import CommentOperation
from schemas.operations.comment_options_operation import CommentOptionsOperation
from schemas.operations.convert_operation import ConvertOperation
from schemas.operations.create_claimed_account_operation import CreateClaimedAccountOperation
from schemas.operations.create_proposal_operation import CreateProposalOperation
from schemas.operations.custom_binary_operation import CustomBinaryOperation
from schemas.operations.custom_json_operation import CustomJsonOperation
from schemas.operations.custom_operation import CustomOperation
from schemas.operations.decline_voting_rights_operation import DeclineVotingRightsOperation
from schemas.operations.delegate_rc_operation import DelegateRcOperation
from schemas.operations.delegate_vesting_shares_operation import DelegateVestingSharesOperation
from schemas.operations.delete_comment_operation import DeleteCommentOperation
from schemas.operations.escrow_approve_operation import EscrowApproveOperation
from schemas.operations.escrow_dispute_operation import EscrowDisputeOperation
from schemas.operations.escrow_release_operation import EscrowReleaseOperation
from schemas.operations.escrow_transfer_operation import EscrowTransferOperation
from schemas.operations.feed_publish_operation import FeedPublishOperation
from schemas.operations.follow_operation import FollowOperation
from schemas.operations.limit_order_cancel_operation import LimitOrderCancelOperation
from schemas.operations.limit_order_create2_operation import LimitOrderCreate2Operation
from schemas.operations.limit_order_create_operation import LimitOrderCreateOperation
from schemas.operations.pow2_operation import Pow2Operation
from schemas.operations.pow_operation import PowOperation
from schemas.operations.recover_account_operation import RecoverAccountOperation
from schemas.operations.recurrent_transfer_operation import RecurrentTransferOperation
from schemas.operations.remove_proposal_operation import RemoveProposalOperation
from schemas.operations.request_account_recovery_operation import RequestAccountRecoveryOperation
from schemas.operations.reset_account_operation import ResetAccountOperation
from schemas.operations.set_reset_account_operation import SetResetAccountOperation
from schemas.operations.set_withdraw_vesting_route_operation import SetWithdrawVestingRouteOperation
from schemas.operations.transfer_from_savings_operation import TransferFromSavingsOperation
from schemas.operations.transfer_operation import TransferOperation
from schemas.operations.transfer_to_savings_operation import TransferToSavingsOperation
from schemas.operations.transfer_to_vesting_operation import TransferToVestingOperation
from schemas.operations.update_proposal_operation import UpdateProposalOperation
from schemas.operations.update_proposal_votes_operation import UpdateProposalVotesOperation
from schemas.operations.vote_operation import VoteOperation
from schemas.operations.withdraw_vesting_operation import WithdrawVestingOperation
from schemas.operations.witness_block_approve_operation import WitnessBlockApproveOperation
from schemas.operations.witness_set_properties_operation import WitnessSetPropertiesOperation
from schemas.operations.witness_update_operation import WitnessUpdateOperation, WitnessUpdateOperationLegacy

GenericRepresentibleT = TypeVar("GenericRepresentibleT", bound=Representible)

class HF26Representation(PreconfiguredBaseModel, Generic[GenericRepresentibleT]):
    value: GenericRepresentibleT

    def shallow_dict(self) -> dict[str, Any]:
        return {"type":self.type_, "value": self.value}

    def dict(self, *, exclude: set[str] | None = None, exclude_none: bool = False, exclude_defaults: bool = False) -> DictStrAny:
            result = super().dict(exclude=exclude,exclude_none=exclude_none, exclude_defaults=exclude_defaults)
            result["type"] = self.type_
            return result

    @property
    def type_(self) -> str:
        if isinstance(self.value, OperationBase):
            return self.value.get_name_with_suffix()
        return self.value.get_name()

    @overload
    def __getitem__(self, idx: Literal[0]) -> str: ...
    @overload
    def __getitem__(self, idx: Literal[1]) -> GenericRepresentibleT: ...
    @overload
    def __getitem__(self, idx: str) -> Any: ...

    def __getitem__(self, idx: Literal[0, 1] | str) -> str | GenericRepresentibleT | Any:
        if idx == 0:
            return self.type_
        if idx == 1:
            return self.value
        return super().__getitem__(idx)


class LegacyRepresentation(PreconfiguredBaseModel, Generic[GenericRepresentibleT]):
    value: GenericRepresentibleT

    @property
    def type_(self) -> str:
        return self.value.get_name()

    @overload  # type: ignore [override]
    def __getitem__(self, idx: Literal[0]) -> str: ...
    @overload
    def __getitem__(self, idx: Literal[1]) -> GenericRepresentibleT: ...

    def __getitem__(self, idx: Literal[0, 1]) -> str | GenericRepresentibleT:
        if idx == 0:
            return self.type_
        if idx == 1:
            return self.value
        raise ValueError("Index out of bound <0; 1>")

class HF26RepresentationAccountCreateOperation(HF26Representation[AccountCreateOperation], tag=AccountCreateOperation.get_name_with_suffix()):
            value: AccountCreateOperation


class LegacyRepresentationAccountCreateOperation(LegacyRepresentation[AccountCreateOperation], tag=AccountCreateOperation.get_name(), array_like=True):
            value: AccountCreateOperation


class HF26RepresentationAccountCreateWithDelegationOperation(HF26Representation[AccountCreateWithDelegationOperation], tag=AccountCreateWithDelegationOperation.get_name_with_suffix()):
            value: AccountCreateWithDelegationOperation


class LegacyRepresentationAccountCreateWithDelegationOperation(LegacyRepresentation[AccountCreateWithDelegationOperation], tag=AccountCreateWithDelegationOperation.get_name(), array_like=True):
            value: AccountCreateWithDelegationOperation


class HF26RepresentationAccountUpdate2Operation(HF26Representation[AccountUpdate2Operation], tag=AccountUpdate2Operation.get_name_with_suffix()):
            value: AccountUpdate2Operation


class LegacyRepresentationAccountUpdate2Operation(LegacyRepresentation[AccountUpdate2Operation], tag=AccountUpdate2Operation.get_name(), array_like=True):
            value: AccountUpdate2Operation


class HF26RepresentationAccountUpdateOperation(HF26Representation[AccountUpdateOperation], tag=AccountUpdateOperation.get_name_with_suffix()):
            value: AccountUpdateOperation


class LegacyRepresentationAccountUpdateOperation(LegacyRepresentation[AccountUpdateOperation], tag=AccountUpdateOperation.get_name(), array_like=True):
            value: AccountUpdateOperation


class HF26RepresentationAccountWitnessProxyOperation(HF26Representation[AccountWitnessProxyOperation], tag=AccountWitnessProxyOperation.get_name_with_suffix()):
            value: AccountWitnessProxyOperation


class LegacyRepresentationAccountWitnessProxyOperation(LegacyRepresentation[AccountWitnessProxyOperation], tag=AccountWitnessProxyOperation.get_name(), array_like=True):
            value: AccountWitnessProxyOperation


class HF26RepresentationAccountWitnessVoteOperation(HF26Representation[AccountWitnessVoteOperation], tag=AccountWitnessVoteOperation.get_name_with_suffix()):
            value: AccountWitnessVoteOperation


class LegacyRepresentationAccountWitnessVoteOperation(LegacyRepresentation[AccountWitnessVoteOperation], tag=AccountWitnessVoteOperation.get_name(), array_like=True):
            value: AccountWitnessVoteOperation


class HF26RepresentationCancelTransferFromSavingsOperation(HF26Representation[CancelTransferFromSavingsOperation], tag=CancelTransferFromSavingsOperation.get_name_with_suffix()):
            value: CancelTransferFromSavingsOperation


class LegacyRepresentationCancelTransferFromSavingsOperation(LegacyRepresentation[CancelTransferFromSavingsOperation], tag=CancelTransferFromSavingsOperation.get_name(), array_like=True):
            value: CancelTransferFromSavingsOperation


class HF26RepresentationChangeRecoveryAccountOperation(HF26Representation[ChangeRecoveryAccountOperation], tag=ChangeRecoveryAccountOperation.get_name_with_suffix()):
            value: ChangeRecoveryAccountOperation


class LegacyRepresentationChangeRecoveryAccountOperation(LegacyRepresentation[ChangeRecoveryAccountOperation], tag=ChangeRecoveryAccountOperation.get_name(), array_like=True):
            value: ChangeRecoveryAccountOperation


class HF26RepresentationClaimAccountOperation(HF26Representation[ClaimAccountOperation], tag=ClaimAccountOperation.get_name_with_suffix()):
            value: ClaimAccountOperation


class LegacyRepresentationClaimAccountOperation(LegacyRepresentation[ClaimAccountOperation], tag=ClaimAccountOperation.get_name(), array_like=True):
            value: ClaimAccountOperation


class HF26RepresentationClaimRewardBalanceOperation(HF26Representation[ClaimRewardBalanceOperation], tag=ClaimRewardBalanceOperation.get_name_with_suffix()):
            value: ClaimRewardBalanceOperation


class LegacyRepresentationClaimRewardBalanceOperation(LegacyRepresentation[ClaimRewardBalanceOperation], tag=ClaimRewardBalanceOperation.get_name(), array_like=True):
            value: ClaimRewardBalanceOperation


class HF26RepresentationCollateralizedConvertOperation(HF26Representation[CollateralizedConvertOperation], tag=CollateralizedConvertOperation.get_name_with_suffix()):
            value: CollateralizedConvertOperation


class LegacyRepresentationCollateralizedConvertOperation(LegacyRepresentation[CollateralizedConvertOperation], tag=CollateralizedConvertOperation.get_name(), array_like=True):
            value: CollateralizedConvertOperation


class HF26RepresentationCommentOperation(HF26Representation[CommentOperation], tag=CommentOperation.get_name_with_suffix()):
            value: CommentOperation


class LegacyRepresentationCommentOperation(LegacyRepresentation[CommentOperation], tag=CommentOperation.get_name(), array_like=True):
            value: CommentOperation


class HF26RepresentationCommentOptionsOperation(HF26Representation[CommentOptionsOperation], tag=CommentOptionsOperation.get_name_with_suffix()):
            value: CommentOptionsOperation


class LegacyRepresentationCommentOptionsOperation(LegacyRepresentation[CommentOptionsOperation], tag=CommentOptionsOperation.get_name(), array_like=True):
            value: CommentOptionsOperation


class HF26RepresentationConvertOperation(HF26Representation[ConvertOperation], tag=ConvertOperation.get_name_with_suffix()):
            value: ConvertOperation


class LegacyRepresentationConvertOperation(LegacyRepresentation[ConvertOperation], tag=ConvertOperation.get_name(), array_like=True):
            value: ConvertOperation


class HF26RepresentationCreateClaimedAccountOperation(HF26Representation[CreateClaimedAccountOperation], tag=CreateClaimedAccountOperation.get_name_with_suffix()):
            value: CreateClaimedAccountOperation


class LegacyRepresentationCreateClaimedAccountOperation(LegacyRepresentation[CreateClaimedAccountOperation], tag=CreateClaimedAccountOperation.get_name(), array_like=True):
            value: CreateClaimedAccountOperation


class HF26RepresentationCreateProposalOperation(HF26Representation[CreateProposalOperation], tag=CreateProposalOperation.get_name_with_suffix()):
            value: CreateProposalOperation


class LegacyRepresentationCreateProposalOperation(LegacyRepresentation[CreateProposalOperation], tag=CreateProposalOperation.get_name(), array_like=True):
            value: CreateProposalOperation


class HF26RepresentationCustomBinaryOperation(HF26Representation[CustomBinaryOperation], tag=CustomBinaryOperation.get_name_with_suffix()):
            value: CustomBinaryOperation


class LegacyRepresentationCustomBinaryOperation(LegacyRepresentation[CustomBinaryOperation], tag=CustomBinaryOperation.get_name(), array_like=True):
            value: CustomBinaryOperation


class HF26RepresentationCustomJsonOperation(HF26Representation[CustomJsonOperation], tag=CustomJsonOperation.get_name_with_suffix()):
            value: CustomJsonOperation


class LegacyRepresentationCustomJsonOperation(LegacyRepresentation[CustomJsonOperation], tag=CustomJsonOperation.get_name(), array_like=True):
            value: CustomJsonOperation


class HF26RepresentationCustomOperation(HF26Representation[CustomOperation], tag=CustomOperation.get_name_with_suffix()):
            value: CustomOperation


class LegacyRepresentationCustomOperation(LegacyRepresentation[CustomOperation], tag=CustomOperation.get_name(), array_like=True):
            value: CustomOperation


class HF26RepresentationDeclineVotingRightsOperation(HF26Representation[DeclineVotingRightsOperation], tag=DeclineVotingRightsOperation.get_name_with_suffix()):
            value: DeclineVotingRightsOperation


class LegacyRepresentationDeclineVotingRightsOperation(LegacyRepresentation[DeclineVotingRightsOperation], tag=DeclineVotingRightsOperation.get_name(), array_like=True):
            value: DeclineVotingRightsOperation


class HF26RepresentationDelegateRcOperation(HF26Representation[DelegateRcOperation], tag=DelegateRcOperation.get_name_with_suffix()):
            value: DelegateRcOperation


class LegacyRepresentationDelegateRcOperation(LegacyRepresentation[DelegateRcOperation], tag=DelegateRcOperation.get_name(), array_like=True):
            value: DelegateRcOperation


class HF26RepresentationDelegateVestingSharesOperation(HF26Representation[DelegateVestingSharesOperation], tag=DelegateVestingSharesOperation.get_name_with_suffix()):
            value: DelegateVestingSharesOperation


class LegacyRepresentationDelegateVestingSharesOperation(LegacyRepresentation[DelegateVestingSharesOperation], tag=DelegateVestingSharesOperation.get_name(), array_like=True):
            value: DelegateVestingSharesOperation


class HF26RepresentationDeleteCommentOperation(HF26Representation[DeleteCommentOperation], tag=DeleteCommentOperation.get_name_with_suffix()):
            value: DeleteCommentOperation


class LegacyRepresentationDeleteCommentOperation(LegacyRepresentation[DeleteCommentOperation], tag=DeleteCommentOperation.get_name(), array_like=True):
            value: DeleteCommentOperation


class HF26RepresentationEscrowApproveOperation(HF26Representation[EscrowApproveOperation], tag=EscrowApproveOperation.get_name_with_suffix()):
            value: EscrowApproveOperation


class LegacyRepresentationEscrowApproveOperation(LegacyRepresentation[EscrowApproveOperation], tag=EscrowApproveOperation.get_name(), array_like=True):
            value: EscrowApproveOperation


class HF26RepresentationEscrowDisputeOperation(HF26Representation[EscrowDisputeOperation], tag=EscrowDisputeOperation.get_name_with_suffix()):
            value: EscrowDisputeOperation


class LegacyRepresentationEscrowDisputeOperation(LegacyRepresentation[EscrowDisputeOperation], tag=EscrowDisputeOperation.get_name(), array_like=True):
            value: EscrowDisputeOperation


class HF26RepresentationEscrowReleaseOperation(HF26Representation[EscrowReleaseOperation], tag=EscrowReleaseOperation.get_name_with_suffix()):
            value: EscrowReleaseOperation


class LegacyRepresentationEscrowReleaseOperation(LegacyRepresentation[EscrowReleaseOperation], tag=EscrowReleaseOperation.get_name(), array_like=True):
            value: EscrowReleaseOperation


class HF26RepresentationEscrowTransferOperation(HF26Representation[EscrowTransferOperation], tag=EscrowTransferOperation.get_name_with_suffix()):
            value: EscrowTransferOperation


class LegacyRepresentationEscrowTransferOperation(LegacyRepresentation[EscrowTransferOperation], tag=EscrowTransferOperation.get_name(), array_like=True):
            value: EscrowTransferOperation


class HF26RepresentationFeedPublishOperation(HF26Representation[FeedPublishOperation], tag=FeedPublishOperation.get_name_with_suffix()):
            value: FeedPublishOperation


class LegacyRepresentationFeedPublishOperation(LegacyRepresentation[FeedPublishOperation], tag=FeedPublishOperation.get_name(), array_like=True):
            value: FeedPublishOperation


class HF26RepresentationFollowOperation(HF26Representation[FollowOperation], tag=FollowOperation.get_name_with_suffix()):
            value: FollowOperation


class LegacyRepresentationFollowOperation(LegacyRepresentation[FollowOperation], tag=FollowOperation.get_name(), array_like=True):
            value: FollowOperation


class HF26RepresentationLimitOrderCancelOperation(HF26Representation[LimitOrderCancelOperation], tag=LimitOrderCancelOperation.get_name_with_suffix()):
            value: LimitOrderCancelOperation


class LegacyRepresentationLimitOrderCancelOperation(LegacyRepresentation[LimitOrderCancelOperation], tag=LimitOrderCancelOperation.get_name(), array_like=True):
            value: LimitOrderCancelOperation


class HF26RepresentationLimitOrderCreate2Operation(HF26Representation[LimitOrderCreate2Operation], tag=LimitOrderCreate2Operation.get_name_with_suffix()):
            value: LimitOrderCreate2Operation


class LegacyRepresentationLimitOrderCreate2Operation(LegacyRepresentation[LimitOrderCreate2Operation], tag=LimitOrderCreate2Operation.get_name(), array_like=True):
            value: LimitOrderCreate2Operation


class HF26RepresentationLimitOrderCreateOperation(HF26Representation[LimitOrderCreateOperation], tag=LimitOrderCreateOperation.get_name_with_suffix()):
            value: LimitOrderCreateOperation


class LegacyRepresentationLimitOrderCreateOperation(LegacyRepresentation[LimitOrderCreateOperation], tag=LimitOrderCreateOperation.get_name(), array_like=True):
            value: LimitOrderCreateOperation


class HF26RepresentationPow2Operation(HF26Representation[Pow2Operation], tag=Pow2Operation.get_name_with_suffix()):
            value: Pow2Operation


class LegacyRepresentationPow2Operation(LegacyRepresentation[Pow2Operation], tag=Pow2Operation.get_name(), array_like=True):
            value: Pow2Operation


class HF26RepresentationPowOperation(HF26Representation[PowOperation], tag=PowOperation.get_name_with_suffix()):
            value: PowOperation


class LegacyRepresentationPowOperation(LegacyRepresentation[PowOperation], tag=PowOperation.get_name(), array_like=True):
            value: PowOperation


class HF26RepresentationRecoverAccountOperation(HF26Representation[RecoverAccountOperation], tag=RecoverAccountOperation.get_name_with_suffix()):
            value: RecoverAccountOperation


class LegacyRepresentationRecoverAccountOperation(LegacyRepresentation[RecoverAccountOperation], tag=RecoverAccountOperation.get_name(), array_like=True):
            value: RecoverAccountOperation


class HF26RepresentationRecurrentTransferOperation(HF26Representation[RecurrentTransferOperation], tag=RecurrentTransferOperation.get_name_with_suffix()):
            value: RecurrentTransferOperation


class LegacyRepresentationRecurrentTransferOperation(LegacyRepresentation[RecurrentTransferOperation], tag=RecurrentTransferOperation.get_name(), array_like=True):
            value: RecurrentTransferOperation


class HF26RepresentationRemoveProposalOperation(HF26Representation[RemoveProposalOperation], tag=RemoveProposalOperation.get_name_with_suffix()):
            value: RemoveProposalOperation


class LegacyRepresentationRemoveProposalOperation(LegacyRepresentation[RemoveProposalOperation], tag=RemoveProposalOperation.get_name(), array_like=True):
            value: RemoveProposalOperation


class HF26RepresentationRequestAccountRecoveryOperation(HF26Representation[RequestAccountRecoveryOperation], tag=RequestAccountRecoveryOperation.get_name_with_suffix()):
            value: RequestAccountRecoveryOperation


class LegacyRepresentationRequestAccountRecoveryOperation(LegacyRepresentation[RequestAccountRecoveryOperation], tag=RequestAccountRecoveryOperation.get_name(), array_like=True):
            value: RequestAccountRecoveryOperation


class HF26RepresentationResetAccountOperation(HF26Representation[ResetAccountOperation], tag=ResetAccountOperation.get_name_with_suffix()):
            value: ResetAccountOperation


class LegacyRepresentationResetAccountOperation(LegacyRepresentation[ResetAccountOperation], tag=ResetAccountOperation.get_name(), array_like=True):
            value: ResetAccountOperation


class HF26RepresentationSetResetAccountOperation(HF26Representation[SetResetAccountOperation], tag=SetResetAccountOperation.get_name_with_suffix()):
            value: SetResetAccountOperation


class LegacyRepresentationSetResetAccountOperation(LegacyRepresentation[SetResetAccountOperation], tag=SetResetAccountOperation.get_name(), array_like=True):
            value: SetResetAccountOperation


class HF26RepresentationSetWithdrawVestingRouteOperation(HF26Representation[SetWithdrawVestingRouteOperation], tag=SetWithdrawVestingRouteOperation.get_name_with_suffix()):
            value: SetWithdrawVestingRouteOperation


class LegacyRepresentationSetWithdrawVestingRouteOperation(LegacyRepresentation[SetWithdrawVestingRouteOperation], tag=SetWithdrawVestingRouteOperation.get_name(), array_like=True):
            value: SetWithdrawVestingRouteOperation


class HF26RepresentationTransferFromSavingsOperation(HF26Representation[TransferFromSavingsOperation], tag=TransferFromSavingsOperation.get_name_with_suffix()):
            value: TransferFromSavingsOperation


class LegacyRepresentationTransferFromSavingsOperation(LegacyRepresentation[TransferFromSavingsOperation], tag=TransferFromSavingsOperation.get_name(), array_like=True):
            value: TransferFromSavingsOperation


class HF26RepresentationTransferOperation(HF26Representation[TransferOperation], tag=TransferOperation.get_name_with_suffix()):
            value: TransferOperation


class LegacyRepresentationTransferOperation(LegacyRepresentation[TransferOperation], tag=TransferOperation.get_name(), array_like=True):
            value: TransferOperation


class HF26RepresentationTransferToSavingsOperation(HF26Representation[TransferToSavingsOperation], tag=TransferToSavingsOperation.get_name_with_suffix()):
            value: TransferToSavingsOperation


class LegacyRepresentationTransferToSavingsOperation(LegacyRepresentation[TransferToSavingsOperation], tag=TransferToSavingsOperation.get_name(), array_like=True):
            value: TransferToSavingsOperation


class HF26RepresentationTransferToVestingOperation(HF26Representation[TransferToVestingOperation], tag=TransferToVestingOperation.get_name_with_suffix()):
            value: TransferToVestingOperation


class LegacyRepresentationTransferToVestingOperation(LegacyRepresentation[TransferToVestingOperation], tag=TransferToVestingOperation.get_name(), array_like=True):
            value: TransferToVestingOperation


class HF26RepresentationUpdateProposalOperation(HF26Representation[UpdateProposalOperation], tag=UpdateProposalOperation.get_name_with_suffix()):
            value: UpdateProposalOperation


class LegacyRepresentationUpdateProposalOperation(LegacyRepresentation[UpdateProposalOperation], tag=UpdateProposalOperation.get_name(), array_like=True):
            value: UpdateProposalOperation


class HF26RepresentationUpdateProposalVotesOperation(HF26Representation[UpdateProposalVotesOperation], tag=UpdateProposalVotesOperation.get_name_with_suffix()):
            value: UpdateProposalVotesOperation


class LegacyRepresentationUpdateProposalVotesOperation(LegacyRepresentation[UpdateProposalVotesOperation], tag=UpdateProposalVotesOperation.get_name(), array_like=True):
            value: UpdateProposalVotesOperation


class HF26RepresentationVoteOperation(HF26Representation[VoteOperation], tag=VoteOperation.get_name_with_suffix()):
            value: VoteOperation


class LegacyRepresentationVoteOperation(LegacyRepresentation[VoteOperation], tag=VoteOperation.get_name(), array_like=True):
            value: VoteOperation


class HF26RepresentationWithdrawVestingOperation(HF26Representation[WithdrawVestingOperation], tag=WithdrawVestingOperation.get_name_with_suffix()):
            value: WithdrawVestingOperation


class LegacyRepresentationWithdrawVestingOperation(LegacyRepresentation[WithdrawVestingOperation], tag=WithdrawVestingOperation.get_name(), array_like=True):
            value: WithdrawVestingOperation


class HF26RepresentationWitnessBlockApproveOperation(HF26Representation[WitnessBlockApproveOperation], tag=WitnessBlockApproveOperation.get_name_with_suffix()):
            value: WitnessBlockApproveOperation


class LegacyRepresentationWitnessBlockApproveOperation(LegacyRepresentation[WitnessBlockApproveOperation], tag=WitnessBlockApproveOperation.get_name(), array_like=True):
            value: WitnessBlockApproveOperation


class HF26RepresentationWitnessSetPropertiesOperation(HF26Representation[WitnessSetPropertiesOperation], tag=WitnessSetPropertiesOperation.get_name_with_suffix()):
            value: WitnessSetPropertiesOperation


class LegacyRepresentationWitnessSetPropertiesOperation(LegacyRepresentation[WitnessSetPropertiesOperation], tag=WitnessSetPropertiesOperation.get_name(), array_like=True):
            value: WitnessSetPropertiesOperation


class HF26RepresentationWitnessUpdateOperation(HF26Representation[WitnessUpdateOperation], tag=WitnessUpdateOperation.get_name_with_suffix()):
            value: WitnessUpdateOperation


class LegacyRepresentationWitnessUpdateOperation(LegacyRepresentation[WitnessUpdateOperation], tag=WitnessUpdateOperation.get_name(), array_like=True):
            value: WitnessUpdateOperationLegacy
