# fmt: off

# WARNING: This code was automatically generated by a script.
# DO NOT EDIT this file manually, as any changes may be overwritten.
# If modifications are needed, please update the generating script instead.

from __future__ import annotations

from typing import Literal, overload

import msgspec

from schemas.operation import Operation

from schemas.operations.account_create_operation import AccountCreateOperation
from schemas.operations.account_create_with_delegation_operation import AccountCreateWithDelegationOperation
from schemas.operations.account_update2_operation import AccountUpdate2Operation
from schemas.operations.account_update_operation import AccountUpdateOperation
from schemas.operations.account_witness_proxy_operation import AccountWitnessProxyOperation
from schemas.operations.account_witness_vote_operation import AccountWitnessVoteOperation
from schemas.operations.cancel_transfer_from_savings_operation import CancelTransferFromSavingsOperation
from schemas.operations.change_recovery_account_operation import ChangeRecoveryAccountOperation
from schemas.operations.claim_account_operation import ClaimAccountOperation
from schemas.operations.claim_reward_balance_operation import ClaimRewardBalanceOperation
from schemas.operations.collateralized_convert_operation import CollateralizedConvertOperation
from schemas.operations.comment_operation import CommentOperation
from schemas.operations.comment_options_operation import CommentOptionsOperation
from schemas.operations.convert_operation import ConvertOperation
from schemas.operations.create_claimed_account_operation import CreateClaimedAccountOperation
from schemas.operations.create_proposal_operation import CreateProposalOperation
from schemas.operations.custom_binary_operation import CustomBinaryOperation
from schemas.operations.custom_json_operation import CustomJsonOperation
from schemas.operations.custom_operation import CustomOperation
from schemas.operations.decline_voting_rights_operation import DeclineVotingRightsOperation
from schemas.operations.delegate_vesting_shares_operation import DelegateVestingSharesOperation
from schemas.operations.delete_comment_operation import DeleteCommentOperation
from schemas.operations.escrow_approve_operation import EscrowApproveOperation
from schemas.operations.escrow_dispute_operation import EscrowDisputeOperation
from schemas.operations.escrow_release_operation import EscrowReleaseOperation
from schemas.operations.escrow_transfer_operation import EscrowTransferOperation
from schemas.operations.feed_publish_operation import FeedPublishOperation
from schemas.operations.limit_order_cancel_operation import LimitOrderCancelOperation
from schemas.operations.limit_order_create2_operation import LimitOrderCreate2Operation
from schemas.operations.limit_order_create_operation import LimitOrderCreateOperation
from schemas.operations.pow_operation import PowOperation
from schemas.operations.pow2_operation import Pow2Operation
from schemas.operations.recover_account_operation import RecoverAccountOperation
from schemas.operations.recurrent_transfer_operation import RecurrentTransferOperation
from schemas.operations.remove_proposal_operation import RemoveProposalOperation
from schemas.operations.request_account_recovery_operation import RequestAccountRecoveryOperation
from schemas.operations.reset_account_operation import ResetAccountOperation
from schemas.operations.set_reset_account_operation import SetResetAccountOperation
from schemas.operations.set_withdraw_vesting_route_operation import SetWithdrawVestingRouteOperation
from schemas.operations.transfer_from_savings_operation import TransferFromSavingsOperation
from schemas.operations.transfer_operation import TransferOperation
from schemas.operations.transfer_to_savings_operation import TransferToSavingsOperation
from schemas.operations.transfer_to_vesting_operation import TransferToVestingOperation
from schemas.operations.update_proposal_operation import UpdateProposalOperation
from schemas.operations.update_proposal_votes_operation import UpdateProposalVotesOperation
from schemas.operations.vote_operation import VoteOperation
from schemas.operations.withdraw_vesting_operation import WithdrawVestingOperation
from schemas.operations.witness_block_approve_operation import WitnessBlockApproveOperation
from schemas.operations.witness_set_properties_operation import WitnessSetPropertiesOperation
from schemas.operations.witness_update_operation import WitnessUpdateOperation

class HF26Representation(msgspec.Struct):
    value: Operation
    
    @property
    def type_(self) -> str:
        return self.value.get_name_with_suffix()
    
        
class LegacyRepresentation(msgspec.Struct):
    value: Operation
    
    @property
    def type_(self) -> str:
        return self.value.get_name()
    
    @overload
    def __getitem__(self, idx: Literal[0]) -> str: ...
    @overload
    def __getitem__(self, idx: Literal[1]) -> Operation: ...

    def __getitem__(self, idx: Literal[0, 1]) -> str | Operation:
        if idx == 0:
            return self.type_
        elif idx == 1:
            return self.value
        raise ValueError("Index out of bound <0; 1>")

class HF26RepresentationAccountCreateOperation(HF26Representation, tag="account_create_operation"):
            value: AccountCreateOperation


class HF26RepresentationAccountCreateWithDelegationOperation(HF26Representation, tag="account_create_with_delegation_operation"):
            value: AccountCreateWithDelegationOperation


class HF26RepresentationAccountUpdate2Operation(HF26Representation, tag="account_update2_operation"):
            value: AccountUpdate2Operation


class HF26RepresentationAccountUpdateOperation(HF26Representation, tag="account_update_operation"):
            value: AccountUpdateOperation


class HF26RepresentationAccountWitnessProxyOperation(HF26Representation, tag="account_witness_proxy_operation"):
            value: AccountWitnessProxyOperation


class HF26RepresentationAccountWitnessVoteOperation(HF26Representation, tag="account_witness_vote_operation"):
            value: AccountWitnessVoteOperation


class HF26RepresentationCancelTransferFromSavingsOperation(HF26Representation, tag="cancel_transfer_from_savings_operation"):
            value: CancelTransferFromSavingsOperation


class HF26RepresentationChangeRecoveryAccountOperation(HF26Representation, tag="change_recovery_account_operation"):
            value: ChangeRecoveryAccountOperation


class HF26RepresentationClaimAccountOperation(HF26Representation, tag="claim_account_operation"):
            value: ClaimAccountOperation


class HF26RepresentationClaimRewardBalanceOperation(HF26Representation, tag="claim_reward_balance_operation"):
            value: ClaimRewardBalanceOperation


class HF26RepresentationCollateralizedConvertOperation(HF26Representation, tag="collateralized_convert_operation"):
            value: CollateralizedConvertOperation


class HF26RepresentationCommentOperation(HF26Representation, tag="comment_operation"):
            value: CommentOperation


class HF26RepresentationCommentOptionsOperation(HF26Representation, tag="comment_options_operation"):
            value: CommentOptionsOperation


class HF26RepresentationConvertOperation(HF26Representation, tag="convert_operation"):
            value: ConvertOperation


class HF26RepresentationCreateClaimedAccountOperation(HF26Representation, tag="create_claimed_account_operation"):
            value: CreateClaimedAccountOperation


class HF26RepresentationCreateProposalOperation(HF26Representation, tag="create_proposal_operation"):
            value: CreateProposalOperation


class HF26RepresentationCustomBinaryOperation(HF26Representation, tag="custom_binary_operation"):
            value: CustomBinaryOperation


class HF26RepresentationCustomJsonOperation(HF26Representation, tag="custom_json_operation"):
            value: CustomJsonOperation


class HF26RepresentationCustomOperation(HF26Representation, tag="custom_operation"):
            value: CustomOperation


class HF26RepresentationDeclineVotingRightsOperation(HF26Representation, tag="decline_voting_rights_operation"):
            value: DeclineVotingRightsOperation


class HF26RepresentationDelegateVestingSharesOperation(HF26Representation, tag="delegate_vesting_shares_operation"):
            value: DelegateVestingSharesOperation


class HF26RepresentationDeleteCommentOperation(HF26Representation, tag="delete_comment_operation"):
            value: DeleteCommentOperation


class HF26RepresentationEscrowApproveOperation(HF26Representation, tag="escrow_approve_operation"):
            value: EscrowApproveOperation


class HF26RepresentationEscrowDisputeOperation(HF26Representation, tag="escrow_dispute_operation"):
            value: EscrowDisputeOperation


class HF26RepresentationEscrowReleaseOperation(HF26Representation, tag="escrow_release_operation"):
            value: EscrowReleaseOperation


class HF26RepresentationEscrowTransferOperation(HF26Representation, tag="escrow_transfer_operation"):
            value: EscrowTransferOperation


class HF26RepresentationFeedPublishOperation(HF26Representation, tag="feed_publish_operation"):
            value: FeedPublishOperation


class HF26RepresentationLimitOrderCancelOperation(HF26Representation, tag="limit_order_cancel_operation"):
            value: LimitOrderCancelOperation


class HF26RepresentationLimitOrderCreate2Operation(HF26Representation, tag="limit_order_create2_operation"):
            value: LimitOrderCreate2Operation


class HF26RepresentationLimitOrderCreateOperation(HF26Representation, tag="limit_order_create_operation"):
            value: LimitOrderCreateOperation


class HF26RepresentationPowOperation(HF26Representation, tag="pow_operation"):
            value: PowOperation


class HF26RepresentationPow2Operation(HF26Representation, tag="pow2_operation"):
            value: Pow2Operation


class HF26RepresentationRecoverAccountOperation(HF26Representation, tag="recover_account_operation"):
            value: RecoverAccountOperation


class HF26RepresentationRecurrentTransferOperation(HF26Representation, tag="recurrent_transfer_operation"):
            value: RecurrentTransferOperation


class HF26RepresentationRemoveProposalOperation(HF26Representation, tag="remove_proposal_operation"):
            value: RemoveProposalOperation


class HF26RepresentationRequestAccountRecoveryOperation(HF26Representation, tag="request_account_recovery_operation"):
            value: RequestAccountRecoveryOperation


class HF26RepresentationResetAccountOperation(HF26Representation, tag="reset_account_operation"):
            value: ResetAccountOperation


class HF26RepresentationSetResetAccountOperation(HF26Representation, tag="set_reset_account_operation"):
            value: SetResetAccountOperation


class HF26RepresentationSetWithdrawVestingRouteOperation(HF26Representation, tag="set_withdraw_vesting_route_operation"):
            value: SetWithdrawVestingRouteOperation


class HF26RepresentationTransferFromSavingsOperation(HF26Representation, tag="transfer_from_savings_operation"):
            value: TransferFromSavingsOperation


class HF26RepresentationTransferOperation(HF26Representation, tag="transfer_operation"):
            value: TransferOperation


class HF26RepresentationTransferToSavingsOperation(HF26Representation, tag="transfer_to_savings_operation"):
            value: TransferToSavingsOperation


class HF26RepresentationTransferToVestingOperation(HF26Representation, tag="transfer_to_vesting_operation"):
            value: TransferToVestingOperation


class HF26RepresentationUpdateProposalOperation(HF26Representation, tag="update_proposal_operation"):
            value: UpdateProposalOperation


class HF26RepresentationUpdateProposalVotesOperation(HF26Representation, tag="update_proposal_votes_operation"):
            value: UpdateProposalVotesOperation


class HF26RepresentationVoteOperation(HF26Representation, tag="vote_operation"):
            value: VoteOperation


class HF26RepresentationWithdrawVestingOperation(HF26Representation, tag="withdraw_vesting_operation"):
            value: WithdrawVestingOperation


class HF26RepresentationWitnessBlockApproveOperation(HF26Representation, tag="witness_block_approve_operation"):
            value: WitnessBlockApproveOperation


class HF26RepresentationWitnessSetPropertiesOperation(HF26Representation, tag="witness_set_properties_operation"):
            value: WitnessSetPropertiesOperation


class HF26RepresentationWitnessUpdateOperation(HF26Representation, tag="witness_update_operation"):
            value: WitnessUpdateOperation


class LegacyRepresentationAccountCreateOperationLegacy(LegacyRepresentation, tag="account_create_operat", array_like=True):
            value: AccountCreateOperation


class LegacyRepresentationAccountCreateWithDelegationOperationLegacy(LegacyRepresentation, tag="account_create_with_delegation_operat", array_like=True):
            value: AccountCreateWithDelegationOperation


class LegacyRepresentationClaimAccountOperationLegacy(LegacyRepresentation, tag="claim_account_operat", array_like=True):
            value: ClaimAccountOperation


class LegacyRepresentationClaimRewardBalanceOperationLegacy(LegacyRepresentation, tag="claim_reward_balance_operat", array_like=True):
            value: ClaimRewardBalanceOperation


class LegacyRepresentationCollateralizedConvertOperationLegacy(LegacyRepresentation, tag="collateralized_convert_operat", array_like=True):
            value: CollateralizedConvertOperation


class LegacyRepresentationCommentOptionsOperationLegacy(LegacyRepresentation, tag="comment_options_operat", array_like=True):
            value: CommentOptionsOperation


class LegacyRepresentationConvertOperationLegacy(LegacyRepresentation, tag="convert_operat", array_like=True):
            value: ConvertOperation


class LegacyRepresentationCreateProposalOperationLegacy(LegacyRepresentation, tag="create_proposal_operat", array_like=True):
            value: CreateProposalOperation


class LegacyRepresentationDelegateVestingSharesOperationLegacy(LegacyRepresentation, tag="delegate_vesting_shares_operat", array_like=True):
            value: DelegateVestingSharesOperation


class LegacyRepresentationPowOperationLegacy(LegacyRepresentation, tag="pow_operat", array_like=True):
            value: PowOperation


class LegacyRepresentationPow2OperationLegacy(LegacyRepresentation, tag="pow2_operat", array_like=True):
            value: Pow2Operation


class LegacyRepresentationEscrowReleaseOperationLegacy(LegacyRepresentation, tag="escrow_release_operat", array_like=True):
            value: EscrowReleaseOperation


class LegacyRepresentationEscrowTransferOperationLegacy(LegacyRepresentation, tag="escrow_transfer_operat", array_like=True):
            value: EscrowTransferOperation


class LegacyRepresentationLimitOrderCreate2OperationLegacy(LegacyRepresentation, tag="limit_order_create2_operat", array_like=True):
            value: LimitOrderCreate2Operation


class LegacyRepresentationLimitOrderCreateOperationLegacy(LegacyRepresentation, tag="limit_order_create_operat", array_like=True):
            value: LimitOrderCreateOperation


class LegacyRepresentationRecurrentTransferOperationLegacy(LegacyRepresentation, tag="recurrent_transfer_operat", array_like=True):
            value: RecurrentTransferOperation


class LegacyRepresentationTransferFromSavingsOperationLegacy(LegacyRepresentation, tag="transfer_from_savings_operat", array_like=True):
            value: TransferFromSavingsOperation


class LegacyRepresentationTransferOperationLegacy(LegacyRepresentation, tag="transfer_operat", array_like=True):
            value: TransferOperation


class LegacyRepresentationTransferToSavingsOperationLegacy(LegacyRepresentation, tag="transfer_to_savings_operat", array_like=True):
            value: TransferToSavingsOperation


class LegacyRepresentationTransferToVestingOperationLegacy(LegacyRepresentation, tag="transfer_to_vesting_operat", array_like=True):
            value: TransferToVestingOperation


class LegacyRepresentationUpdateProposalOperationLegacy(LegacyRepresentation, tag="update_proposal_operat", array_like=True):
            value: UpdateProposalOperation


class LegacyRepresentationWithdrawVestingOperationLegacy(LegacyRepresentation, tag="withdraw_vesting_operat", array_like=True):
            value: WithdrawVestingOperation


class LegacyRepresentationWitnessUpdateOperationLegacy(LegacyRepresentation, tag="witness_update_operat", array_like=True):
            value: WitnessUpdateOperation


